/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.vistaPlanilla;

import Controlador.clsBitacora;
import Controlador.controladorPlanilla.clsConceptoExcepción;
import Controlador.clsUsuarioConectado;
import Modelo.BitacoraDAO;
import Modelo.Conexion;
import Modelo.modeloPlanilla.ConceptoExcepciónDAO;


import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;


import java.awt.Desktop;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author marlo
 */
public class frmConceptoExcepción extends javax.swing.JFrame {

    /**
     * Creates new form ConceptoExcepción
     */
    public frmConceptoExcepción() {
        initComponents();
        llenadoDeTablas();
    }
    
    private clsBitacora crearBitacora(String accion) {

        clsBitacora bitacora = new clsBitacora();

        try {

            BitacoraDAO dao = new BitacoraDAO();

            int usuario = 1;

            try {

                usuario = clsUsuarioConectado.getUsuId();

            } catch (Exception e) {

                System.out.println("Usuario no definido");
            }

            bitacora.setUsucodigo(usuario);

            bitacora.setAplcodigo(2);

            bitacora.setBitfecha(dao.fechaActual());

            bitacora.setBitip(
                    java.net.InetAddress.getLocalHost().getHostAddress()
            );

            bitacora.setBitequipo(
                    java.net.InetAddress.getLocalHost().getHostName()
            );

            bitacora.setBitaccion(accion);

        } catch (Exception e) {

            e.printStackTrace();
        }

        return bitacora;
    }

     public void llenadoDeTablas() {

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Codigo Excepcion");
        modelo.addColumn("Codigo Concepto");
        modelo.addColumn("Codigo Empleado");

        tblExcepciones.setModel(modelo);

        ConceptoExcepciónDAO dao =
                new ConceptoExcepciónDAO();

        DefaultTableModel tabla =
                dao.listarExcepcionesEnTabla();

        for (int i = 0; i < tabla.getRowCount(); i++) {

            String[] dato = new String[3];

            dato[0] = tabla.getValueAt(i, 0).toString();
            dato[1] = tabla.getValueAt(i, 1).toString();
            dato[2] = tabla.getValueAt(i, 2).toString();

            modelo.addRow(dato);
        }
    }

    public void limpiarTextos() {

        txtCodigo.setText("");
        txtConcepto.setText("");
        txtEmpleado.setText("");
        txtBuscar.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtConcepto = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExcepciones = new javax.swing.JTable();
        btnSalida = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Concepto Excepción");

        jLabel2.setText("Código");

        jLabel3.setText("Código Concepto");

        jLabel4.setText("Código Empleado");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnReporte.setText("Reportes");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblExcepciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código Concepto", "Código Empleado"
            }
        ));
        jScrollPane1.setViewportView(tblExcepciones);

        btnSalida.setText("Salida");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        btnAyuda.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnAyuda.setText("?");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(81, 81, 81)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar)
                                    .addComponent(btnBuscar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalida)
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAyuda)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSalida)
                    .addComponent(btnAyuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnReporte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if(txtConcepto.getText().trim().isEmpty() ||
           txtEmpleado.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(
                    null,
                    "Complete los campos"
            );

            return;
        }

        try {

            clsConceptoExcepción excepcion =
                    new clsConceptoExcepción();

            excepcion.setConCodigo(
                    Integer.parseInt(txtConcepto.getText())
            );

            excepcion.setEmpCodigo(
                    Integer.parseInt(txtEmpleado.getText())
            );

            ConceptoExcepciónDAO dao =
                    new ConceptoExcepciónDAO();

            clsBitacora bitacora =
                    crearBitacora("Insertar excepción");

            int resultado =
                    dao.insertarExcepcion(excepcion, bitacora);

            if(resultado > 0){

                JOptionPane.showMessageDialog(
                        null,
                        "Excepción registrada"
                );

                llenadoDeTablas();

                limpiarTextos();

            }else{

                JOptionPane.showMessageDialog(
                        null,
                        "No se pudo registrar"
                );
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Ingrese números válidos"
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Error: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
         if(txtCodigo.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(
                    null,
                    "Seleccione un registro"
            );

            return;
        }

        if(txtConcepto.getText().trim().isEmpty() ||
           txtEmpleado.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(
                    null,
                    "Complete los campos"
            );

            return;
        }

        try {

            clsConceptoExcepción excepcion =
                    new clsConceptoExcepción();

            excepcion.setExcCodigo(
                    Integer.parseInt(txtCodigo.getText())
            );

            excepcion.setConCodigo(
                    Integer.parseInt(txtConcepto.getText())
            );

            excepcion.setEmpCodigo(
                    Integer.parseInt(txtEmpleado.getText())
            );

            ConceptoExcepciónDAO dao =
                    new ConceptoExcepciónDAO();

            clsBitacora bitacora =
                    crearBitacora("Modificar excepción");

            int resultado =
                    dao.actualizarExcepcion(excepcion, bitacora);

            if(resultado > 0){

                JOptionPane.showMessageDialog(
                        null,
                        "Excepción modificada"
                );

                llenadoDeTablas();

                limpiarTextos();

            }else{

                JOptionPane.showMessageDialog(
                        null,
                        "No se pudo modificar"
                );
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Código inválido"
            );
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null,
                    "Ingrese un código");

            return;
        }

        try {

            clsConceptoExcepción excepcion =
                    new clsConceptoExcepción();

            excepcion.setExcCodigo(
                    Integer.parseInt(txtCodigo.getText())
            );

            ConceptoExcepciónDAO dao =
                    new ConceptoExcepciónDAO();

            clsBitacora bitacora =
                    crearBitacora("Eliminar excepción");

            int resultado =
                    dao.eliminarExcepcion(excepcion, bitacora);

            if(resultado > 0){

                JOptionPane.showMessageDialog(null,
                        "Excepción eliminada");

                llenadoDeTablas();

                limpiarTextos();

            }else{

                JOptionPane.showMessageDialog(null,
                        "No se pudo eliminar");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,
                    "Código inválido");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarTextos();

    habilitarBotones();
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        Map p = new HashMap();
        JasperReport report;
        JasperPrint print;
        try {
            conn = Conexion.getConnection();
            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                + "/src/main/java/Reportes/ReportesPlanilla/reporteConceptoExcepcion.jrxml");
            print = JasperFillManager.fillReport(report, p, conn);
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("Reporte Prueba");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(txtBuscar.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(
                    null,
                    "Ingrese un ID"
            );

            return;
        }

        try {

            int id =
                    Integer.parseInt(txtBuscar.getText());

            ConceptoExcepciónDAO dao =
                    new ConceptoExcepciónDAO();

            clsBitacora bitacora =
                    crearBitacora("Buscar excepción");

            clsConceptoExcepción excepcion =
                    dao.obtenerExcepcionPorId(id, bitacora);

            if(excepcion != null){

                txtCodigo.setText(
                        String.valueOf(
                                excepcion.getExcCodigo()
                        )
                );

                txtConcepto.setText(
                        String.valueOf(
                                excepcion.getConCodigo()
                        )
                );

                txtEmpleado.setText(
                        String.valueOf(
                                excepcion.getEmpCodigo()
                        )
                );

            }else{

                JOptionPane.showMessageDialog(
                        null,
                        "Registro no encontrado"
                );
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Ingrese un número válido"
            );
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAyudaActionPerformed

     public void habilitarBotones() {

        btnRegistrar.setEnabled(true);

        btnModificar.setEnabled(true);

        btnEliminar.setEnabled(true);
    }

    public void desHabilitarBotones() {

        btnRegistrar.setEnabled(false);

        btnModificar.setEnabled(false);

        btnEliminar.setEnabled(false);
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConceptoExcepción.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConceptoExcepción.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConceptoExcepción.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConceptoExcepción.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConceptoExcepción().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExcepciones;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtEmpleado;
    // End of variables declaration//GEN-END:variables
}
