/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.vistaPlanilla;
import Modelo.modeloPlanilla.PlanillaDetalleDAO;
import Controlador.controladorPlanilla.clsPlanillaDetalle;
import Controlador.clsBitacora;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author andre
 */
public class frmDetalle extends javax.swing.JFrame {
// 1. DECLARACIONES GLOBALES (Esto quita los errores de 'dao')
    private final PlanillaDetalleDAO dao = new PlanillaDetalleDAO();
    private final clsBitacora bitacora = new clsBitacora();

    public frmDetalle() {
        initComponents(); // Inicializa los componentes de NetBeans
        this.setLocationRelativeTo(null); // Centra la ventana
        this.setTitle("Mantenimiento Detalle de Planilla");
        
        // Bloqueamos los campos automáticos
        txtDetCodigo.setEditable(false);
        txtLiquido.setEditable(false);
        
        llenarTabla(); // Carga los datos de la DB
    }

    // 2. MÉTODO PARA CARGAR LOS DATOS EN LA TABLA
    public void llenarTabla() {
        try {
            // Asegúrate de que el JTable se llame 'tblPlanillaDetalle'
            DefaultTableModel modelo = dao.listarPlanillaDetalleEnTabla();
            tblPlanillaDetalle.setModel(modelo);
        } catch (Exception e) {
            System.out.println("Error al llenar tabla: " + e.getMessage());
        }
    }

    // 3. MÉTODO PARA LIMPIAR LOS TEXTFIELD
    private void limpiarCampos() {
        txtDetCodigo.setText("");
        txtPlaCodigo.setText("");
        txtEmpCodigo.setText("");
        txtSalario.setText("");
        txtPercepciones.setText("");
        txtDeducciones.setText("");
        txtLiquido.setText("");
        txtBusqueda.setText("");
    }
    /**
     * Creates new form frmDetalle
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDetCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmpCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPercepciones = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPlaCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDeducciones = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlanillaDetalle = new javax.swing.JTable();
        txtLiquido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("ok");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel5.setText("Buscar por código:");

        jLabel1.setText("Codigo");

        txtDetCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo de Empleado");

        txtEmpCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpCodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Salario");

        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingreso Extra");

        txtPercepciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPercepcionesActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo de planilla");

        txtPlaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlaCodigoActionPerformed(evt);
            }
        });

        jLabel7.setText("Deducciones");

        txtDeducciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeduccionesActionPerformed(evt);
            }
        });

        jLabel8.setText("Salario Liquido");

        tblPlanillaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Detalle", "ID Planilla", "Salario Base", "Percepciones", "Deducciones", "Liquido"
            }
        ));
        jScrollPane1.setViewportView(tblPlanillaDetalle);

        txtLiquido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLiquidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
                        .addComponent(btnSalir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtDetCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtPercepciones, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSalario))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnEliminar)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnGuardar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnModificar))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDeducciones, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtPlaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(7, 7, 7))
                                        .addComponent(txtLiquido))))
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmpCodigo)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDetCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtEmpCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPercepciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDeducciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPlaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(28, 28, 28)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnGuardar)
                                    .addComponent(btnModificar)
                                    .addComponent(btnNuevo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBuscar)
                                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

      try {
        // 1. VALIDAR QUE EL CAMPO DE BÚSQUEDA NO ESTÉ VACÍO
        if (txtBusqueda.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un código para buscar");
            txtBusqueda.requestFocus();
            return;
        }

        // 2. OBTENER EL ID DEL CAMPO DE TEXTO
        int id = Integer.parseInt(txtBusqueda.getText().trim());

        // 3. INSTANCIAR DAO Y BITÁCORA
        Modelo.modeloPlanilla.PlanillaDetalleDAO dao = new Modelo.modeloPlanilla.PlanillaDetalleDAO();
        Controlador.clsBitacora bitacora = new Controlador.clsBitacora();

        // 4. EJECUTAR LA BÚSQUEDA
        Controlador.controladorPlanilla.clsPlanillaDetalle detalle = dao.obtenerPlanillaDetallePorId(id, bitacora);

        // 5. VALIDAR RESULTADO Y LLENAR CAMPOS
        if (detalle != null) {
            txtDetCodigo.setText(String.valueOf(detalle.getDetcodigo()));
            txtPlaCodigo.setText(String.valueOf(detalle.getPlacodigo()));
            txtEmpCodigo.setText(String.valueOf(detalle.getEmpcodigo()));
            txtSalario.setText(String.valueOf(detalle.getDetsalario()));
            txtPercepciones.setText(String.valueOf(detalle.getDettotalpercepciones()));
            txtDeducciones.setText(String.valueOf(detalle.getDettotaldeducciones()));
            txtLiquido.setText(String.valueOf(detalle.getDetliquido()));

            JOptionPane.showMessageDialog(null, "Registro encontrado");

        } else {
            // SI NO ENCUENTRA NADA, LIMPIAMOS LOS CAMPOS
            JOptionPane.showMessageDialog(null, "Detalle de planilla no encontrado");
            limpiarCampos(); // Llamamos al método que ya creamos antes
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese un código numérico válido");
        txtBusqueda.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            // 1. Validaciones básicas de campos vacíos
            if (txtPlaCodigo.getText().trim().isEmpty() || txtEmpCodigo.getText().trim().isEmpty() || txtSalario.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, llene los campos obligatorios (Planilla, Empleado y Salario)");
                return;
            }

            // 2. Crear la entidad y setear los datos de los JTextFields
            clsPlanillaDetalle detalle = new clsPlanillaDetalle();

            detalle.setPlacodigo(Integer.parseInt(txtPlaCodigo.getText().trim()));
            detalle.setEmpcodigo(Integer.parseInt(txtEmpCodigo.getText().trim()));

            // Convertimos los montos de texto a double
            double sueldoBase = Double.parseDouble(txtSalario.getText().trim());
            double percepciones = txtPercepciones.getText().trim().isEmpty() ? 0 : Double.parseDouble(txtPercepciones.getText().trim());
            double deducciones = txtDeducciones.getText().trim().isEmpty() ? 0 : Double.parseDouble(txtDeducciones.getText().trim());

            // 3. Cálculo del Líquido (Operación lógica)
            double liquido = sueldoBase + percepciones - deducciones;

            // Asignamos al objeto
            detalle.setDetsalario(sueldoBase);
            detalle.setDettotalpercepciones(percepciones);
            detalle.setDettotaldeducciones(deducciones);
            detalle.setDetliquido(liquido);

            // 4. Ejecutar la inserción mediante el DAO
            PlanillaDetalleDAO dao = new PlanillaDetalleDAO();
            clsBitacora bitacora = new clsBitacora(); // Manteniendo tu estándar de bitácora

            int resultado = dao.insertarPlanillaDetalle(detalle, bitacora);

            // 5. Respuesta al usuario
            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "Detalle de planilla guardado correctamente.\nLíquido calculado: " + liquido);

                // Actualizar la tabla y limpiar campos
              llenarTabla();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar el registro");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Asegúrese de ingresar solo números en los campos de montos e IDs.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // LIMPIAR CAMPOS
      // 1. LIMPIAR TODOS LOS CAMPOS (Usando los nombres de planilla)
    txtDetCodigo.setText("");
    txtPlaCodigo.setText("");
    txtEmpCodigo.setText("");
    txtSalario.setText("");
    txtPercepciones.setText("");
    txtDeducciones.setText("");
    txtLiquido.setText("");
    txtBusqueda.setText("");

    // 2. ACTIVAR CAMPOS PARA EDICIÓN
    txtPlaCodigo.setEnabled(true);
    txtEmpCodigo.setEnabled(true);
    txtSalario.setEnabled(true);
    txtPercepciones.setEnabled(true);
    txtDeducciones.setEnabled(true);
    
    // El ID y el Líquido siempre deben estar bloqueados (son automáticos)
    txtDetCodigo.setEnabled(false);
    txtLiquido.setEnabled(false);

    // 3. CONTROL DE BOTONES (Estado inicial para un nuevo registro)
    btnGuardar.setEnabled(true);
    btnModificar.setEnabled(false);
    btnEliminar.setEnabled(false);

    // 4. DAR ENFOQUE AL PRIMER CAMPO LÓGICO
    txtPlaCodigo.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
     // 1. Validar que el campo del ID no esté vacío
    if (txtDetCodigo.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe seleccionar o buscar un detalle de planilla para eliminar.");
        return;
    }

    // 2. Confirmación de seguridad
    int respuesta = JOptionPane.showConfirmDialog(
        null, 
        "¿Está seguro de eliminar este registro de planilla?", 
        "Confirmar Eliminación", 
        JOptionPane.YES_NO_OPTION
    );

    if (respuesta == JOptionPane.YES_OPTION) {
        try {
            // Instanciar la entidad y el ID a eliminar
            Controlador.controladorPlanilla.clsPlanillaDetalle detalle = new Controlador.controladorPlanilla.clsPlanillaDetalle();
            detalle.setDetcodigo(Integer.parseInt(txtDetCodigo.getText().trim()));

            Modelo.modeloPlanilla.PlanillaDetalleDAO dao = new Modelo.modeloPlanilla.PlanillaDetalleDAO();
            Controlador.clsBitacora bitacora = new Controlador.clsBitacora();

            // 3. Ejecutar la eliminación en la base de datos
            int resultado = dao.eliminarPlanillaDetalle(detalle, bitacora);

            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "Registro de planilla eliminado correctamente.");

                // 4. Limpiar campos y refrescar la tabla visual
                limpiarCampos(); 
                llenarTabla();   

                // 5. Resetear estados de los campos y botones
                txtPlaCodigo.setEnabled(false);
                txtEmpCodigo.setEnabled(false);
                txtSalario.setEnabled(false);
                txtPercepciones.setEnabled(false);
                txtDeducciones.setEnabled(false);
                
                btnGuardar.setEnabled(false);
                btnModificar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnNuevo.setEnabled(true);
                
                txtBusqueda.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro. Verifique si el ID existe.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El código detectado no es un número válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en el sistema: " + e.getMessage());
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    try {
        // 1. VALIDACIÓN DE CAMPOS OBLIGATORIOS
        if (txtDetCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe buscar o seleccionar un registro para modificar.");
            return;
        }

        if (txtSalario.getText().trim().isEmpty() || txtEmpCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El empleado y el salario no pueden estar vacíos.");
            return;
        }

        // 2. CREAR ENTIDAD Y CARGAR DATOS
        Controlador.controladorPlanilla.clsPlanillaDetalle detalle = new Controlador.controladorPlanilla.clsPlanillaDetalle();

        // Seteamos el ID (Vital para el WHERE en SQL)
        detalle.setDetcodigo(Integer.parseInt(txtDetCodigo.getText().trim()));
        detalle.setPlacodigo(Integer.parseInt(txtPlaCodigo.getText().trim()));
        detalle.setEmpcodigo(Integer.parseInt(txtEmpCodigo.getText().trim()));

        // Procesamos montos numéricos
        double sueldo = Double.parseDouble(txtSalario.getText().trim());
        double percepciones = txtPercepciones.getText().trim().isEmpty() ? 0 : Double.parseDouble(txtPercepciones.getText().trim());
        double deducciones = txtDeducciones.getText().trim().isEmpty() ? 0 : Double.parseDouble(txtDeducciones.getText().trim());

        // 3. RE-CALCULAR EL LÍQUIDO
        double liquido = sueldo + percepciones - deducciones;

        detalle.setDetsalario(sueldo);
        detalle.setDettotalpercepciones(percepciones);
        detalle.setDettotaldeducciones(deducciones);
        detalle.setDetliquido(liquido);

        // 4. EJECUTAR ACTUALIZACIÓN
        Modelo.modeloPlanilla.PlanillaDetalleDAO dao = new Modelo.modeloPlanilla.PlanillaDetalleDAO();
        Controlador.clsBitacora bitacora = new Controlador.clsBitacora();

        int resultado = dao.actualizarPlanillaDetalle(detalle, bitacora);

        if (resultado > 0) {
            JOptionPane.showMessageDialog(null, "Registro modificado correctamente.\nNuevo líquido: Q" + liquido);

            // 5. ACTUALIZAR VISTA
            llenarTabla(); // Refresca el JTable
            limpiarCampos(); // Limpia los cuadros de texto
            
            // Resetear botones
            btnGuardar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo modificar el registro.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Verifique que los montos e IDs sean números válidos.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtDetCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetCodigoActionPerformed

    private void txtEmpCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpCodigoActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtPercepcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPercepcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPercepcionesActionPerformed

    private void txtPlaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlaCodigoActionPerformed

    private void txtDeduccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeduccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeduccionesActionPerformed

    private void txtLiquidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLiquidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLiquidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPlanillaDetalle;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDeducciones;
    private javax.swing.JTextField txtDetCodigo;
    private javax.swing.JTextField txtEmpCodigo;
    private javax.swing.JTextField txtLiquido;
    private javax.swing.JTextField txtPercepciones;
    private javax.swing.JTextField txtPlaCodigo;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
