/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.vistaPlanilla;

import Controlador.clsBitacora;
import Controlador.controladorPlanilla.clsEmpleados;
import Controlador.clsUsuarioConectado;
import Controlador.controladorPlanilla.clsBitacoraPlanilla;
import Modelo.BitacoraDAO;
import Modelo.Conexion;
import Modelo.modeloPlanilla.EmpleadosDAO;
import java.awt.Desktop;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import Modelo.modeloPlanilla.BitacoraPlanillaDAO;
import Controlador.controladorPlanilla.clsBitacoraPlanilla;

/**
 *
 * @author marlo
 */
public class frmMantenimientoEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form frmMantenimientoEmpleado
     */
    public frmMantenimientoEmpleado() {
        initComponents();
        
        cboEstado.setModel(
    new javax.swing.DefaultComboBoxModel<>(
        new String[] {
            "Activo",
            "Inactivo"
        }
    )
);
         
        llenadoDeTablas();
    }
    
     private clsBitacora crearBitacora(String accion) {

        clsBitacora bitacora = new clsBitacora();

        try {

            BitacoraDAO dao = new BitacoraDAO();

            int usuario = 1;

            try {
                usuario = clsUsuarioConectado.getUsuId();
            } catch (Exception e) {
                System.out.println("Usuario no definido");
            }

            bitacora.setUsucodigo(usuario);

            bitacora.setAplcodigo(2);

            bitacora.setBitfecha(dao.fechaActual());

            bitacora.setBitip(java.net.InetAddress.getLocalHost().getHostAddress());

            bitacora.setBitequipo(java.net.InetAddress.getLocalHost().getHostName());

            bitacora.setBitaccion(accion);

        } catch (Exception e) {
            e.printStackTrace();
        }

        return bitacora;
    }

    
    public void llenadoDeTablas() {

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("DPI");
        modelo.addColumn("Puesto");
        modelo.addColumn("Fecha Ingreso");
        modelo.addColumn("Estado");

        tblEmpleados.setModel(modelo);

        EmpleadosDAO dao = new EmpleadosDAO();

        clsBitacora bitacora = crearBitacora("Consulta empleados");

        List<clsEmpleados> lista = dao.obtenerEmpleados(bitacora);

        String[] dato = new String[6];

        for (clsEmpleados e : lista) {

            dato[0] = String.valueOf(e.getEmpcodigo());
            dato[1] = e.getEmpnombre();
            dato[2] = e.getEmpdpi();
            dato[3] = String.valueOf(e.getPuecodigo());
            dato[4] = String.valueOf(e.getEmpfecha_ingreso());
            dato[5] = String.valueOf(e.getEmpestado());

            modelo.addRow(dato);
        }
    }
    
    
    public void limpiarTextos() {

        txtCodigo.setText("");
        txtNombre.setText("");
        txtDPI.setText("");
        txtPuesto.setText("");
        txtFechaIngreso.setText("");
        cboEstado.setSelectedIndex(0);
        txtBuscar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        btnReporte = new javax.swing.JButton();
        cboEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtDPI = new javax.swing.JTextField();
        btnAyuda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtPuesto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Estado");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "DPI", "Cod.puesto", "Fecha_ingreso", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleados);

        btnReporte.setText("Reportes");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo Puesto");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Mantenimiento De Empleados");

        btnAyuda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAyuda.setText("?");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel7.setText("Fecha De Ingreso");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel5.setText("DPI");

        btnSalir.setText("Salida");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel2))
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCodigo)
                                            .addComponent(txtNombre)
                                            .addComponent(txtDPI)
                                            .addComponent(txtPuesto)
                                            .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnLimpiar)
                                                    .addComponent(btnRegistrar))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnModificar)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnEliminar))
                                                    .addComponent(btnReporte)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(btnBuscar)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(291, 291, 291)
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnReporte))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarTextos();

        habilitarBotones();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null,
                "Ingrese un código");

            return;
        }

        try {

            clsEmpleados empleado = new clsEmpleados();

            empleado.setEmpcodigo(
                Integer.parseInt(txtCodigo.getText())
            );

            EmpleadosDAO dao = new EmpleadosDAO();

            clsBitacora bitacora = crearBitacora("Eliminar empleado");

            int resultado = dao.eliminarEmpleado(empleado, bitacora);

            if(resultado > 0){
                
        BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6003);

            bitacoraPlanilla.setAccion("Eliminar");

            bitacoraPlanilla.setTablaAfectada("empleados");

            bitacoraPlanilla.setDescripcion(
            "Se elimino un empleado"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );

            

                JOptionPane.showMessageDialog(null,
                    "Empleado eliminado");

                llenadoDeTablas();

                limpiarTextos();

            }else{

                JOptionPane.showMessageDialog(null,
                    "No se pudo eliminar");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,
                "Código inválido");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        Map p = new HashMap();
        JasperReport report;
        JasperPrint print;
        try {
            conn = Conexion.getConnection();
            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                + "/src/main/java/Reportes/ReportesPlanilla/empleadoReporte.jrxml");
            print = JasperFillManager.fillReport(report, p, conn);
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("Reporte Prueba");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
        try {

            String ruta = new File("src/main/java/Ayudas/Planillas/AyudaEmpleados.chm").getAbsolutePath();

            File archivo = new File(ruta);

            if (archivo.exists()) {

                Runtime.getRuntime().exec(
                    "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
                );

            } else {

                JOptionPane.showMessageDialog(this, "No se encontró el archivo de ayuda");

            }

        } catch (Exception ex) {

            ex.printStackTrace();

        }
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if(txtNombre.getText().trim().isEmpty() ||
            txtDPI.getText().trim().isEmpty() ||
            txtPuesto.getText().trim().isEmpty() ||
            txtFechaIngreso.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null, "Complete los campos");
            return;
        }

        try {

            clsEmpleados empleado = new clsEmpleados();

            empleado.setEmpnombre(txtNombre.getText().trim());

            empleado.setEmpdpi(txtDPI.getText().trim());

            empleado.setPuecodigo(
                Integer.parseInt(txtPuesto.getText())
            );

            empleado.setEmpfecha_ingreso(
                java.sql.Date.valueOf(txtFechaIngreso.getText())
            );

            // Estado desde ComboBox
            if(cboEstado.getSelectedItem().toString().equals("Activo")){

                empleado.setEmpestado(1);

            }else{

                empleado.setEmpestado(0);
            }

            EmpleadosDAO dao = new EmpleadosDAO();

            clsBitacora bitacora = crearBitacora("Insertar empleado");

            int resultado = dao.insertarEmpleado(empleado, bitacora);

            if(resultado > 0){
                
            BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6003);

            bitacoraPlanilla.setAccion("Registrar");

            bitacoraPlanilla.setTablaAfectada("empleados");

            bitacoraPlanilla.setDescripcion(
            "Se registró un empleado"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );

            


                llenadoDeTablas();

                limpiarTextos();

            }else{

                JOptionPane.showMessageDialog(null,
                    "No se pudo registrar.\n" +
                    "Verifique:\n" +
                    "- DPI duplicado\n" +
                    "- Puesto existente\n" +
                    "- Bitácora\n" +
                    "- Fecha");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Código de puesto inválido");

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(null,
                "Fecha inválida. Use formato YYYY-MM-DD");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
                "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(txtBuscar.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null, "Ingrese un ID");
            return;
        }

        try {

            int id = Integer.parseInt(txtBuscar.getText());

            EmpleadosDAO dao = new EmpleadosDAO();

            clsBitacora bitacora = crearBitacora("Buscar empleado");

            clsEmpleados empleado = dao.obtenerEmpleadoPorId(id, bitacora);

            if(empleado != null){
                
            BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6003);

            bitacoraPlanilla.setAccion("Buscar");

            bitacoraPlanilla.setTablaAfectada("empleados");

            bitacoraPlanilla.setDescripcion(
            "Se Busqueda un empleado"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );

               

                txtCodigo.setText(String.valueOf(empleado.getEmpcodigo()));

                txtNombre.setText(empleado.getEmpnombre());

                txtDPI.setText(empleado.getEmpdpi());

                txtPuesto.setText(
                    String.valueOf(empleado.getPuecodigo())
                );

                txtFechaIngreso.setText(
                    String.valueOf(empleado.getEmpfecha_ingreso())
                );

                if(empleado.getEmpestado() == 1){

                    cboEstado.setSelectedItem("Activo");

                }else{

                    cboEstado.setSelectedItem("Inactivo");
                }

            }else{

                JOptionPane.showMessageDialog(null, "Empleado no encontrado");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Ingrese un número válido");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null, "Seleccione un registro");
            return;
        }

        if(txtNombre.getText().trim().isEmpty() ||
            txtDPI.getText().trim().isEmpty() ||
            txtPuesto.getText().trim().isEmpty() ||
            txtFechaIngreso.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null, "Complete los campos");
            return;
        }

        try {

            clsEmpleados empleado = new clsEmpleados();

            empleado.setEmpcodigo(
                Integer.parseInt(txtCodigo.getText())
            );

            empleado.setEmpnombre(
                txtNombre.getText().trim()
            );

            empleado.setEmpdpi(
                txtDPI.getText().trim()
            );

            empleado.setPuecodigo(
                Integer.parseInt(txtPuesto.getText())
            );

            empleado.setEmpfecha_ingreso(
                java.sql.Date.valueOf(txtFechaIngreso.getText())
            );

            if(cboEstado.getSelectedItem().toString().equals("Activo")){

                empleado.setEmpestado(1);

            }else{

                empleado.setEmpestado(0);
            }

            EmpleadosDAO dao = new EmpleadosDAO();

            clsBitacora bitacora = crearBitacora("Modificar empleado");

            int resultado = dao.actualizarEmpleado(empleado, bitacora);

            if(resultado > 0){
                
            BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6003);

            bitacoraPlanilla.setAccion("Modificar");

            bitacoraPlanilla.setTablaAfectada("empleados");

            bitacoraPlanilla.setDescripcion(
            "Se modificacion un empleado"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );

               

                JOptionPane.showMessageDialog(null, "Empleado modificado");

                llenadoDeTablas();

                limpiarTextos();

            }else{

                JOptionPane.showMessageDialog(null,
                    "No se pudo modificar");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,
                "Código inválido");

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(null,
                "Fecha inválida. Use YYYY-MM-DD");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void habilitarBotones() {

        btnRegistrar.setEnabled(true);

        btnModificar.setEnabled(true);

        btnEliminar.setEnabled(true);
    }

    public void desHabilitarBotones() {

        btnRegistrar.setEnabled(false);

        btnModificar.setEnabled(false);

        btnEliminar.setEnabled(false);
    }

    public void esperar5min() {

        try {

            Thread.sleep(5 * 60 * 1000);

        } catch (Exception e) {

            System.out.println(e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenimientoEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDPI;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuesto;
    // End of variables declaration//GEN-END:variables
}
