/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.vistaPlanilla;
import Modelo.modeloPlanilla.PuestoDAO;
import Controlador.controladorPlanilla.clsPuesto;
import Controlador.clsBitacora;
import Controlador.controladorPlanilla.clsBitacoraPlanilla;
import Modelo.modeloPlanilla.BitacoraPlanillaDAO;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class frmPuesto1 extends javax.swing.JFrame {

  public frmPuesto1() {
        initComponents(); // Llama al código que ya tienes abajo
        this.setLocationRelativeTo(null); // Centra la ventana
        llenarTabla(); // Carga los datos de la DB a la tabla
    }

    // 2. MÉTODO PARA CARGAR LOS DATOS EN LA TABLA
    public void llenarTabla() {
        try {
            // Asegúrate de que el nombre 'tblPuesto' sea el mismo que el de tu tabla
            Modelo.modeloPlanilla.PuestoDAO dao = new Modelo.modeloPlanilla.PuestoDAO();
            javax.swing.table.DefaultTableModel modelo = dao.listarPuestosEnTabla();
            tblPuesto.setModel(modelo);
        } catch (Exception e) {
            System.out.println("Error al llenar tabla: " + e.getMessage());
        }
    }

    // 3. MÉTODO PARA LIMPIAR LOS TEXTFIELD
    private void limpiarCampos() {
        CodigoPuesto.setText("");
        NombrePuesto.setText("");
        salario.setText("");
        txtBuscar.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        CodigoPuesto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPuesto = new javax.swing.JTable();
        NombrePuesto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        salario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("ok");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel1.setText("MANTENIMIENTO DE PUESTO");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        CodigoPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoPuestoActionPerformed(evt);
            }
        });

        jLabel5.setText("Buscar por código:");

        jLabel2.setText("Codigo");

        tblPuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Salario Base"
            }
        ));
        jScrollPane1.setViewportView(tblPuesto);

        NombrePuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePuestoActionPerformed(evt);
            }
        });

        jLabel3.setText("Puesto");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioActionPerformed(evt);
            }
        });

        jLabel4.setText("salario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(231, 231, 231)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnSalir)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodigoPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombrePuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnNuevo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnGuardar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnModificar))
                                .addComponent(btnEliminar)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)))
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CodigoPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombrePuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnModificar)
                            .addComponent(btnNuevo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try {

        // VALIDAR
        if (txtBuscar.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Ingrese un código"
            );

            txtBuscar.requestFocus();

            return;
        }

        // OBTENER ID
        int id = Integer.parseInt(
                txtBuscar.getText().trim()
        );

        // DAO
        PuestoDAO dao = new PuestoDAO();

        clsBitacora bitacora = new clsBitacora();

        // BUSCAR
        clsPuesto puesto =
                dao.obtenerPuestoPorId(
                        id,
                        bitacora
                );

        // VALIDAR RESULTADO
        if (puesto != null) {
            
                  
                
            
        BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6002);

            bitacoraPlanilla.setAccion("Buscar");

            bitacoraPlanilla.setTablaAfectada("Puestos");

            bitacoraPlanilla.setDescripcion(
            "Se ha realizado una busqueda en puestos"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );    
            
            
            

            CodigoPuesto.setText(
                    String.valueOf(
                            puesto.getPuecodigo()
                    )
            );

            NombrePuesto.setText(
                    puesto.getPuenombre()
            );

            salario.setText(
                    puesto.getPuesalarioBase().toString()
            );

            JOptionPane.showMessageDialog(
                    null,
                    "Registro encontrado"
            );

        } else {

            JOptionPane.showMessageDialog(
                    null,
                    "Puesto no encontrado"
            );

            CodigoPuesto.setText("");
            NombrePuesto.setText("");
            salario.setText("");
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                null,
                "Ingrese un código válido"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Error: " + e.getMessage()
        );

        e.printStackTrace();
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      // LIMPIAR CAMPOS
    CodigoPuesto.setText("");

    NombrePuesto.setText("");

    salario.setText("");

    txtBuscar.setText("");

    // ACTIVAR CAMPOS
    NombrePuesto.setEnabled(true);

    salario.setEnabled(true);

    // ACTIVAR BOTONES
    btnGuardar.setEnabled(true);

    btnModificar.setEnabled(false);

    btnEliminar.setEnabled(false);

    // ENFOQUE
    NombrePuesto.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
 try {

        if (CodigoPuesto.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Seleccione un puesto"
            );

            return;
        }

        if (NombrePuesto.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Ingrese el nombre"
            );

            return;
        }

        if (salario.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    null,
                    "Ingrese salario"
            );

            return;
        }

        clsPuesto puesto = new clsPuesto();

        puesto.setPuecodigo(
                Integer.parseInt(
                        CodigoPuesto.getText()
                )
        );

        puesto.setPuenombre(
                NombrePuesto.getText().trim()
        );

        puesto.setPuesalarioBase(
                new java.math.BigDecimal(
                        salario.getText().trim()
                )
        );

        PuestoDAO dao = new PuestoDAO();

        clsBitacora bitacora = new clsBitacora();

        int resultado = dao.actualizarPuesto(
                puesto,
                bitacora
        );

        if (resultado > 0) {

            
                
            
        BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6002);

            bitacoraPlanilla.setAccion("Modificar");

            bitacoraPlanilla.setTablaAfectada("Puestos");

            bitacoraPlanilla.setDescripcion(
            "Modificacion en puestos"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );    
            
            
            llenarTabla();
            
            
            
            JOptionPane.showMessageDialog(
                    null,
                    "Registro modificado"
            );

            tblPuesto.setModel(
                    dao.listarPuestosEnTabla()
            );

            CodigoPuesto.setText("");
            NombrePuesto.setText("");
            salario.setText("");
            txtBuscar.setText("");

        } else {

            JOptionPane.showMessageDialog(
                    null,
                    "Error al modificar"
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Error: " + e.getMessage()
        );

        e.printStackTrace();
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void CodigoPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoPuestoActionPerformed

    private void NombrePuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePuestoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
       try {
        // ... (tus validaciones de nombre y salario)

        clsPuesto puesto = new clsPuesto();
        puesto.setPuenombre(NombrePuesto.getText().trim());
        puesto.setPuesalarioBase(new java.math.BigDecimal(salario.getText().trim()));
        
        // ASIGNA UN VALOR TEMPORAL (Asegúrate que el departamento 1 exista en tu DB)
        puesto.setDepcodigo(1); 

        PuestoDAO dao = new PuestoDAO();
        clsBitacora bitacora = new clsBitacora();

        int resultado = dao.insertarPuesto(puesto, bitacora);

        if (resultado > 0) {
            
                  
                
            
        BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6002);

            bitacoraPlanilla.setAccion("Registrar");

            bitacoraPlanilla.setTablaAfectada("Puestos");

            bitacoraPlanilla.setDescripcion(
            "Registro en puestos"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );    
            
            
            llenarTabla();
            
            
            JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
            // ... (limpiar campos)
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo guardar");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
  // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
      // 1. Validar que el campo no esté vacío para evitar errores de número
    if (CodigoPuesto.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe seleccionar o buscar un registro para eliminar.");
        return;
    }

    // 2. Confirmación opcional (es buena práctica)
    int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este puesto?", "Confirmar", JOptionPane.YES_NO_OPTION);
    
    if (respuesta == JOptionPane.YES_OPTION) {
        try {
            clsPuesto puesto = new clsPuesto();
            // Convertimos el texto a entero
            puesto.setPuecodigo(Integer.parseInt(CodigoPuesto.getText().trim()));

            PuestoDAO dao = new PuestoDAO();
            clsBitacora bitacora = new clsBitacora();

            // Ejecutar la eliminación
            int resultado = dao.eliminarPuesto(puesto, bitacora);

            if (resultado > 0) {
                      
                
            
        BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6002);

            bitacoraPlanilla.setAccion("Eliminar");

            bitacoraPlanilla.setTablaAfectada("Puestos");

            bitacoraPlanilla.setDescripcion(
            "Se ha eliminado un puesto"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );    
            
            llenarTabla();
            
                JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");

                // 3. Limpiar campos y refrescar la tabla visual
                limpiarCampos(); // Método que limpia los JTextField
                llenarTabla();   // <--- ESTA LÍNEA ES CLAVE PARA QUE SE REFLEJE EL CAMBIO

                // 4. Resetear estados de botones
                NombrePuesto.setEnabled(false);
                salario.setEnabled(false);
                btnGuardar.setEnabled(false);
                btnModificar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnNuevo.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El código no es válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPuesto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPuesto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPuesto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPuesto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPuesto1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoPuesto;
    private javax.swing.JTextField NombrePuesto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField salario;
    private javax.swing.JTable tblPuesto;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
