/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.ComercialComprasyVentas;

import Controlador.Compras.clsProveedor;
import Controlador.clsUsuarioConectado;

// 2. Importar clases de la capa Modelo 
import Modelo.Compras.ProveedorDAO;
import Modelo.BitacoraDAO;
import Modelo.PermisosDAO;

// 3. Importar librerías estándar de Java Swing
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.io.File;

import java.lang.Process;


import java.lang.Runtime;

import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

import Modelo.Conexion;


/**
 *
 * @author JENNIFER BARRIOS 
 * ACTUALIZACIÓN: Incorporación de seguridad por perfil, Bypass Admin (ID 1) y control Solo Lectura.
 * Y CORRECCIÓN DE BOTONES
 *
 */

public class frmMantenimientoProveedores extends javax.swing.JFrame {
    ProveedorDAO proveedorDAO = new ProveedorDAO();
    BitacoraDAO bitacoraDAO = new BitacoraDAO();
    PermisosDAO permisosDAO = new PermisosDAO();
    
    private int idUsuarioConectado = clsUsuarioConectado.getUsuId();
    int Aplcodigo = 30004;

    /**
     * Creates new form frmMantenimientoProveedores
     */
    public frmMantenimientoProveedores() {
        initComponents();
        
        // CORRECCIÓN LOCAL: Si no es Admin (ID 1), debe tener permisos mínimos para poder VER el módulo (Buscar)
        if (idUsuarioConectado != 1 && !permisosDAO.puedeBuscar(idUsuarioConectado, Aplcodigo)) {
            JOptionPane.showMessageDialog(null, "No tiene acceso a este módulo para visualizar datos.");
            this.dispose();
            return;
        }
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Seleccione un estado");
        jComboBox1.addItem("Activo");
        jComboBox1.addItem("Inactivo");
        
        llenarTabla();
        cargarPermisosVisuales();
    }

    // Deshabilita o habilita los botones en la carga inicial según permisos (Solo Lectura dinámico)
    public void cargarPermisosVisuales() {
        btnRegistrar.setEnabled(puedeInsertar());
        btnModificarr.setEnabled(puedeModificar());
        btnEliminar.setEnabled(puedeEliminar());
        btnBuscar.setEnabled(puedeBuscar());
    }

    // Métodos lógicos locales con Bypass integrado para Administrador (ID 1)
    private boolean puedeInsertar() {
        if (idUsuarioConectado == 1) return true;
        return permisosDAO.puedeInsertar(idUsuarioConectado, Aplcodigo);
    }

    private boolean puedeModificar() {
        if (idUsuarioConectado == 1) return true;
        return permisosDAO.puedeModificar(idUsuarioConectado, Aplcodigo);
    }

    private boolean puedeEliminar() {
        if (idUsuarioConectado == 1) return true;
        return permisosDAO.puedeEliminar(idUsuarioConectado, Aplcodigo);
    }

    private boolean puedeBuscar() {
        if (idUsuarioConectado == 1) return true;
        return permisosDAO.puedeBuscar(idUsuarioConectado, Aplcodigo);
    }

    public void llenarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("NIT");
        modelo.addColumn("CUENTA");
        modelo.addColumn("CONTACTO");
        modelo.addColumn("DEPTO");
        modelo.addColumn("ESTADO");

        tablaProveedores.setModel(modelo);
        List<clsProveedor> listaProveedores = proveedorDAO.consultaProveedores();

        for (clsProveedor proveedor : listaProveedores) {
            modelo.addRow(new Object[]{
                proveedor.getProcodigo(),
                proveedor.getPronombre(),
                proveedor.getPronit(),
                proveedor.getProcuentabancaria(),
                proveedor.getProcontacto(),
                proveedor.getProdepartamento(),
                proveedor.getProestado()
            });
        }
    }

    public void limpiarCampos() {
        txtProCodigo.setText("");
        txtProNombre.setText("");
        txtProNit.setText("");
        txtProCuenta.setText("");
        txtProContacto.setText("");
        txtProDepto.setText("");
        jComboBox1.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProNombre = new javax.swing.JTextField();
        txtProNit = new javax.swing.JTextField();
        txtProCuenta = new javax.swing.JTextField();
        txtProContacto = new javax.swing.JTextField();
        txtProDepto = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificarr = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "NIT", "CUENTA", "CONTACTO", "DEPTO"
            }
        ));
        jScrollPane2.setViewportView(tablaProveedores);

        jLabel1.setText("PROVEEDORES");

        jLabel2.setText("CODIGO:");

        jLabel3.setText("NOMBRE");

        jLabel4.setText("NIT:");

        jLabel5.setText("CUENTA:");

        jLabel6.setText("CONTACTO:");

        jLabel7.setText("DEPTO:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificarr.setText("Modificar");
        btnModificarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarrActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("ESTADO:");

        jButton6.setText("AYUDA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnSalida.setText("SALIR");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        btnReportes.setText("REPORTES");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtProNit, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addComponent(txtProNombre))
                                    .addComponent(txtProCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProContacto)
                                    .addComponent(txtProDepto)
                                    .addComponent(txtProCuenta, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(87, 87, 87)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrar)
                            .addComponent(btnModificarr)
                            .addComponent(btnEliminar)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpiar))
                        .addGap(57, 57, 57))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtProCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtProNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarr))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtProNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtProCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtProContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtProDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(btnSalida)
                            .addComponent(btnReportes))
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

   // VALIDACIÓN DE PERMISO (Incluye Bypass Admin ID 1)
    if (!puedeInsertar()) {
        JOptionPane.showMessageDialog(null, "No posee permisos para registrar proveedores.");
        return;
    }

    clsProveedor proveedor = new clsProveedor();
    proveedor.setPronombre(txtProNombre.getText());
    proveedor.setPronit(txtProNit.getText());
    proveedor.setProcuentabancaria(txtProCuenta.getText());
    proveedor.setProcontacto(txtProContacto.getText());
    proveedor.setProdepartamento(txtProDepto.getText());
    proveedor.setProestado(jComboBox1.getSelectedItem().toString());

    if (proveedorDAO.ingresarProveedor(proveedor) > 0) {
        JOptionPane.showMessageDialog(null, "Proveedor Registrado con éxito");
        // Registro en bitácora con el ID del usuario actual
        bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Registró Proveedor");
        llenarTabla();
        limpiarCampos();
    }
    
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
if (!puedeBuscar()) {
        JOptionPane.showMessageDialog(null, "No posee permisos para realizar búsquedas.");
        return;
    }

    if (txtProCodigo.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un código para buscar.");
        return;
    }

    clsProveedor proveedor = new clsProveedor();
    proveedor.setProcodigo(Integer.parseInt(txtProCodigo.getText()));
    proveedor = proveedorDAO.consultaProveedorPorId(proveedor);

    if (proveedor.getPronombre() != null) {
        txtProNombre.setText(proveedor.getPronombre());
        txtProNit.setText(proveedor.getPronit());
        txtProCuenta.setText(proveedor.getProcuentabancaria());
        txtProContacto.setText(proveedor.getProcontacto());
        txtProDepto.setText(proveedor.getProdepartamento());
        jComboBox1.setSelectedItem(proveedor.getProestado());
        
        // Registro en bitácora de la consulta realizada
        bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Buscó Proveedor ID: " + txtProCodigo.getText());
    } else {
        JOptionPane.showMessageDialog(null, "Proveedor no encontrado");
    }
    
// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarrActionPerformed
// VALIDACIÓN DE PERMISO (Incluye Bypass Admin ID 1)
    if (!puedeModificar()) {
        JOptionPane.showMessageDialog(null, "No posee permisos para modificar información.");
        return;
    }

    if (txtProCodigo.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe buscar primero un proveedor antes de modificarlo.");
        return;
    }

    clsProveedor proveedor = new clsProveedor();
    proveedor.setProcodigo(Integer.parseInt(txtProCodigo.getText()));
    proveedor.setPronombre(txtProNombre.getText());
    proveedor.setPronit(txtProNit.getText());
    proveedor.setProcuentabancaria(txtProCuenta.getText());
    proveedor.setProcontacto(txtProContacto.getText());
    proveedor.setProdepartamento(txtProDepto.getText());
    proveedor.setProestado(jComboBox1.getSelectedItem().toString());

    if (proveedorDAO.actualizaProveedor(proveedor) > 0) {
        JOptionPane.showMessageDialog(null, "Información actualizada correctamente");
        // Registro en bitácora
        bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Modificó Proveedor ID: " + txtProCodigo.getText());
        llenarTabla();
        limpiarCampos();
    }
    
// TODO add your handling code here:
    }//GEN-LAST:event_btnModificarrActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
if (!puedeEliminar()) {
        JOptionPane.showMessageDialog(null, "No posee permisos para eliminar registros.");
        return;
    }

    if (txtProCodigo.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese el código del proveedor que desea eliminar.");
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este proveedor?", "Confirmar", JOptionPane.YES_NO_OPTION);
    if (confirmacion == 0) {
        clsProveedor proveedor = new clsProveedor();
        proveedor.setProcodigo(Integer.parseInt(txtProCodigo.getText()));
        
        if (proveedorDAO.borrarProveedor(proveedor) > 0) {
            // Registro en bitácora si se eliminó con éxito
            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Eliminó Proveedor ID: " + txtProCodigo.getText());
        }
        llenarTabla();
        limpiarCampos();
    }
    
// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    limpiarCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {
    if ((new File("AyudaComprasHelp.chm")).exists()) {
   
        Process p = Runtime
            .getRuntime()
            .exec("AyudaComprasHelp.chm");
        p.waitFor();
        
    } else {
        
        System.out.println("La ayuda no fue encontrada");
        
    }
    
    System.out.println("Correcto");
    
} catch (Exception ex) {
    ex.printStackTrace();
}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
    this.dispose();
    bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Cerró ventana de mantenimiento de proveedores");
    // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed

        Connection conn = null;
    try {
        
        conn = Conexion.getConexion(); 
        
        String rutaReporte = "src/main/java/Reportes/ComprayVentas/reporteProveedores.jrxml";
        
        JasperReport jasperReport = JasperCompileManager.compileReport(rutaReporte);
        
        Map<String, Object> parametros = new HashMap<>();
        
        // 5. Llenar el reporte con los datos de la DB
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametros, conn);
        
        // 6. Mostrar el reporte en una ventana flotante (Viewer)
        JasperViewer viewer = new JasperViewer(jasperPrint, false); // El 'false' evita que se cierre toda la app al cerrar el reporte
        viewer.setTitle("Reporte de Proveedores");
        viewer.setVisible(true);
        
        bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "Generó Reporte de Proveedores");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al generar el reporte de proveedores: " + ex.getMessage());
        ex.printStackTrace();
    } finally {
      
        try {
            if (conn != null && !conn.isClosed()) {
                conn.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenimientoProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificarr;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtProCodigo;
    private javax.swing.JTextField txtProContacto;
    private javax.swing.JTextField txtProCuenta;
    private javax.swing.JTextField txtProDepto;
    private javax.swing.JTextField txtProNit;
    private javax.swing.JTextField txtProNombre;
    // End of variables declaration//GEN-END:variables
}
