/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
//Boris de Leon 9959-24-6203
package Vista.Logistica;

import Controlador.Logistica.clsLinea;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Modelo.BitacoraDAO;
import Modelo.Logistica.LineaDAO;
import java.io.File; //ferdynand monroy mayo 2026 este import muestra el archivo .chm
import javax.swing.JOptionPane;

/**
 *
 * @author deleo
 */
public class frmLinea extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmMarcas
     */
    public frmLinea() {
        initComponents();
        llenarTabla();
        cargarPermisos();
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        this.setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
    }
    public void cargarPermisos() {
        // Obtener el ID del usuario conectado desde la clase global
        int usuId = Controlador.clsUsuarioConectado.getUsuId();
        Modelo.PermisosDAO permisosDAO = new Modelo.PermisosDAO();

        // CÓDIGO DE APLICACIÓN: Cambiar este número por el código exacto de "Marcas" en BD
        int codigoAplicacion = 2012; 

        // Bloqueo o desbloqueo de botones según la base de datos
        btnRegistrar1.setEnabled(permisosDAO.puedeInsertar(usuId, codigoAplicacion));
        btnModificar1.setEnabled(permisosDAO.puedeModificar(usuId, codigoAplicacion));
        btnEliminar1.setEnabled(permisosDAO.puedeEliminar(usuId, codigoAplicacion));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar1 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        label19 = new javax.swing.JLabel();
        txtbuscado1 = new javax.swing.JTextField();
        btnAyuda = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnReportes1 = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLineas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtComision = new javax.swing.JTextField();

        btnRegistrar1.setText("Registrar");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });

        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        label19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label19.setText("ID a buscar");

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnReportes1.setText("Reportes");
        btnReportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes1ActionPerformed(evt);
            }
        });

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        tablaLineas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Linea", "Nombre", "Estado", "Comision"
            }
        ));
        jScrollPane1.setViewportView(tablaLineas);

        jLabel1.setText("ID Linea");

        jLabel2.setText("Nombre");

        jLabel3.setText("Estado");

        jLabel4.setText("Comision");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        txtComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComision, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtbuscado1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar1)
                    .addComponent(btnEliminar1)
                    .addComponent(btnModificar1))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar1)
                    .addComponent(btnAyuda)
                    .addComponent(btnReportes1))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar1)
                    .addComponent(txtbuscado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label19))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
try {
            clsLinea linea = new clsLinea();
            LineaDAO dao = new LineaDAO();

            linea.setLinNombre(txtNombre.getText());
            
            // Si el texto es "1", lo guarda como true. Si es otra cosa, como false.
            boolean estado = txtEstado.getText().trim().equals("1");
            linea.setLinEstado(estado); 
            
            linea.setLinComision(new java.math.BigDecimal(txtComision.getText()));

            if (dao.insertar(linea)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Línea registrada con éxito.");
                limpiarCampos();
                llenarTabla();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar la línea.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Verifica que la comisión sea un número válido.");
        }

    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed

        limpiarCampos();
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
        //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        try {
        String ruta = "C:\\Users\\ferit\\Desktop\\proyFinalP32K26b\\proyectop32k26b\\proyectop32k26b\\src\\main\\java\\Ayudas\\Logistica\\Logistica.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        try {
            if (txtId.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una línea primero.");
                return;
            }

            clsLinea linea = new clsLinea();
            LineaDAO dao = new LineaDAO();

            linea.setLineaId(Integer.parseInt(txtId.getText()));
            linea.setLinNombre(txtNombre.getText());
            
            boolean estado = txtEstado.getText().trim().equals("1");
            linea.setLinEstado(estado);
            
            linea.setLinComision(new java.math.BigDecimal(txtComision.getText()));

            if (dao.actualizar(linea)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Línea actualizada correctamente.");
                limpiarCampos();
                llenarTabla();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar en la BD.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Verifique los datos ingresados.");
        }
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        String idEliminar = txtId.getText();

        if(idEliminar.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una línea para eliminar.");
            return;
        }

        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, "¿Eliminar línea ID " + idEliminar + "?", "Advertencia", javax.swing.JOptionPane.YES_NO_OPTION);
        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            LineaDAO dao = new LineaDAO();
            if (dao.eliminar(Integer.parseInt(idEliminar))) {
                javax.swing.JOptionPane.showMessageDialog(this, "Línea eliminada.");
                limpiarCampos();
                llenarTabla();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar. Verifique que ningún producto use esta línea.");
            }
        }

    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes1ActionPerformed
        Vista.Logistica.frmReportes ventana = new Vista.Logistica.frmReportes();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReportes1ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed

        String idBuscado = txtbuscado1.getText().trim(); 
        
        if(idBuscado.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el ID a buscar.");
            return;
        }

        LineaDAO dao = new LineaDAO();
        clsLinea linea = dao.buscarPorId(Integer.parseInt(idBuscado));

        if (linea != null) {
            txtId.setText(String.valueOf(linea.getLineaId()));
            txtNombre.setText(linea.getLinNombre());
            txtEstado.setText(linea.isLinEstado() ? "1" : "0");
            txtComision.setText(linea.getLinComision().toString());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Línea no encontrada.");
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComisionActionPerformed
public void limpiarCampos() {
        txtId.setText("");      
        txtNombre.setText("");  
        txtEstado.setText("");
        txtComision.setText(""); // Cajita nueva      
        txtNombre.requestFocus();
    }

    public void llenarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Línea");
        modelo.addColumn("Nombre");
        modelo.addColumn("Estado");
        modelo.addColumn("Comisión");
        
        LineaDAO dao = new LineaDAO();
        List<clsLinea> lista = dao.listar();
        
        Object[] fila = new Object[4];
        for (clsLinea linea : lista) {
            fila[0] = linea.getLineaId();
            fila[1] = linea.getLinNombre();
            // Convertimos el boolean a "1" o "0" para mostrarlo en la tabla
            fila[2] = linea.isLinEstado() ? "1" : "0"; 
            fila[3] = linea.getLinComision();
            modelo.addRow(fila);
        }
        tablaLineas.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JButton btnReportes1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label19;
    private javax.swing.JTable tablaLineas;
    private javax.swing.JTextField txtComision;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtbuscado1;
    // End of variables declaration//GEN-END:variables
}
