/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 24-04-2026  1. Creacion frmMantenimientStock, implementaciones basicas
                              //09-05-2026  2. Implementacion de funcionalidad de botones
                              //11-05-2026  3. Implementacion Marca y Linea
                              //13-05-2026  4. Implementacion CRUD
                              //14-05-2026  5. Implementacion con bitacora 
                              //15-05-2026  6. Mantenimiento general
package Vista.Logistica;
import Controlador.clsUsuarioConectado;
import Modelo.PermisosDAO;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.util.List;
import javax.swing.JOptionPane;
import Modelo.Logistica.ExistenciasDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macoh
 */
public class frmMantenimientoStock extends javax.swing.JInternalFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMantenimientoStock.class.getName());
private DefaultTableModel modeloStock;
    /**
     * Creates new form frmMantenimientoStock
     */
public frmMantenimientoStock() {
        initComponents();
        cargarPermisos(); 
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        
        modeloStock = (DefaultTableModel) tablaStock.getModel();
        tablaStock.setDefaultEditor(Object.class, null);
        
        txtIdExistencias.setEditable(false);
        txtIdExistencias.setEnabled(false);
        
  
      actualizarTabla();
    }

    private void cargarDatosPrueba() {
      modeloStock.addRow(new Object[]{"101", "Martillo", "50", "Unidades", "Truper", "Ferretería"});
    modeloStock.addRow(new Object[]{"102", "Clavos 2 pulg", "200", "Bolsas", "Standley", "Construcción"});
    modeloStock.addRow(new Object[]{"103", "Pintura Látex", "15", "Cubetas", "Sherwin", "Pinturas"});
    };

  
 
    public void cargarPermisos() {
        // Obtener el ID del usuario conectado
        int usuId = clsUsuarioConectado.getUsuId();
        PermisosDAO permisosDAO = new PermisosDAO();

        // 2002 es el código de la aplicación Mantenimiento Stock
        int codigoAplicacion = 2002; 

        btnBuscar.setEnabled(permisosDAO.puedeBuscar(usuId, codigoAplicacion));
           btnModificar.setEnabled(permisosDAO.puedeModificar(usuId, codigoAplicacion));
        btnEliminar.setEnabled(permisosDAO.puedeEliminar(usuId, codigoAplicacion));
        btnReportes.setEnabled(permisosDAO.puedeReportar(usuId, codigoAplicacion));
           btnRegistrar.setEnabled(permisosDAO.puedeInsertar(usuId, codigoAplicacion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboxTipoBusqueda = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAdyda = new javax.swing.JButton();
        label17 = new javax.swing.JLabel();
        txtStockActual = new javax.swing.JTextField();
        label15 = new javax.swing.JLabel();
        txtIdExistencias = new javax.swing.JTextField();
        txtBodegaId = new javax.swing.JTextField();
        label13 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtNombreProducto = new javax.swing.JTextField();
        label21 = new javax.swing.JLabel();
        label16 = new javax.swing.JLabel();
        txtMarcaPedido = new javax.swing.JTextField();
        txtLineaPedido = new javax.swing.JTextField();
        label14 = new javax.swing.JLabel();
        btnReportes = new javax.swing.JButton();
        txtIdProducto1 = new javax.swing.JTextField();
        label18 = new javax.swing.JLabel();
        label19 = new javax.swing.JLabel();

        jButton3.setText("Ayuda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "existenciasID", "ID Producto", "Nombrer", "Stock Actual", "Bodega Id", "Marca", "Linea"
            }
        ));
        tablaStock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaStockAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaStockMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaStock);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Stock");

        cboxTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Producto", "Nombre", "Marca", "Linea" }));
        cboxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoBusquedaActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 227, 250));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAdyda.setText("Ayuda");
        btnAdyda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdydaActionPerformed(evt);
            }
        });

        label17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label17.setText("ID Linea");

        txtStockActual.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtStockActual.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label15.setText("ID Existencias");

        txtIdExistencias.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdExistencias.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtIdExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdExistenciasActionPerformed(evt);
            }
        });

        txtBodegaId.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtBodegaId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtBodegaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodegaIdActionPerformed(evt);
            }
        });

        label13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label13.setText("ID Bodega ");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtNombreProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombreProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label21.setText("Nombre Producto");

        label16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label16.setText("ID Marca");

        txtMarcaPedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtMarcaPedido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtLineaPedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtLineaPedido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label14.setText("Stock Actual");

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        txtIdProducto1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdProducto1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label18.setText("ID Producto");

        label19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label19.setText("*Dar doble click a la fila deseada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLineaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)))
                        .addComponent(btnAdyda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscar))
                                    .addComponent(cboxTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(label21)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombreProducto)
                                        .addComponent(txtStockActual)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBodegaId, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMarcaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(label15)
                            .addComponent(label18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(200, 200, 200))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdyda)
                            .addComponent(btnReportes))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label18)
                                    .addComponent(txtIdProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRegistrar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label21)
                                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label14)
                                    .addComponent(txtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBodegaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMarcaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLineaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label17)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnActualizar)
                                    .addComponent(btnModificar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(label19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaStockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaStockAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaStockAncestorAdded

    private void cboxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoBusquedaActionPerformed
        // TODO add your handling code here:

        // Oculta todos los campos de búsqueda al inicio
        // para evitar que aparezcan controles innecesarios
        /*    txtBuscar.setVisible(false);
        fechaInicio.setVisible(false);
        fechaFin.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        btnBuscar.setVisible(false);
        */
        String seleccion = cboxTipoBusqueda.getSelectedItem().toString();
        switch (seleccion) {
            case "ID":
            buscarPorIDS();
            break;
            case "Nombre":
            buscarPorNombreS();
            break;
           case "Marca":
             buscarPorMarca();
            break;
        case "Linea":
            buscarPorLinea(); 
            break; 
        }
    }//GEN-LAST:event_cboxTipoBusquedaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        
       String filtro = txtBuscar.getText().trim();
    if (filtro.isEmpty()) {
        return;
    }

    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modeloStock);
    tablaStock.setRowSorter(sorter);
    
    String seleccion = cboxTipoBusqueda.getSelectedItem().toString();
    int columnaIndex = 0;

    switch (seleccion) {
        case "ID Producto": columnaIndex = 0; break;
        case "Nombre":      columnaIndex = 1; break;
        case "Marca":       columnaIndex = 4; break;
        case "Linea":       columnaIndex = 5; break;
    }

    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro, columnaIndex));
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    String filtro = txtBuscar.getText().trim();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) tablaStock.getModel());
    tablaStock.setRowSorter(sorter);
    if (filtro.isEmpty()) {
        sorter.setRowFilter(null);
        return;
    }
    int seleccion = cboxTipoBusqueda.getSelectedIndex();
    int columnaIndex = 0;

    if (seleccion == 0) {
        columnaIndex = 0;
        columnaIndex = 1;
    } else if (seleccion == 2) {
        columnaIndex = 2;
    } else {
        columnaIndex = 0;
    }
    try {
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro, columnaIndex));
        
        if (tablaStock.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron coincidencias.");
        }
    } catch (Exception e) {
        System.err.println("Error en filtro: " + e.getMessage());
    }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAdydaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdydaActionPerformed
         Vista.Logistica.frmAyuda ventanaAyuda = new Vista.Logistica.frmAyuda();
    
    ventanaAyuda.setVisible(true);
    ventanaAyuda.setLocationRelativeTo(null);
    
    //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        try {
        String ruta = "C:\\Users\\ferit\\Desktop\\proyFinalP32K26b\\proyectop32k26b\\proyectop32k26b\\src\\main\\java\\Ayudas\\Logistica\\Logistica.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnAdydaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (tablaStock.getRowSorter() != null) {
            tablaStock.setRowSorter(null);
        }

        txtBuscar.setText("");
        cboxTipoBusqueda.setSelectedIndex(0);

        txtIdExistencias.setText("");
        txtNombreProducto.setText("");
        txtStockActual.setText("");
        txtBodegaId.setText("");
        txtBodegaId.setText("");
        txtMarcaPedido.setText("");
        txtLineaPedido.setText("");

        tablaStock.clearSelection();

        JOptionPane.showMessageDialog(this, "Formulario restablecido correctamente.");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    int filaSeleccionada = tablaStock.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una fila de la tabla para eliminar.");
        return;
    }
    int filaModelo = tablaStock.convertRowIndexToModel(filaSeleccionada);
    String idEliminarStr = modeloStock.getValueAt(filaModelo, 0).toString();
    String nombreProducto = modeloStock.getValueAt(filaModelo, 2).toString();

    int respuesta = JOptionPane.showConfirmDialog(this, 
        "¿Está seguro de eliminar el producto: " + nombreProducto + "?\nEsta acción no se puede deshacer.", 
        "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

    if (respuesta == JOptionPane.YES_OPTION) {
        try {
            int idEliminar = Integer.parseInt(idEliminarStr);
            
            ExistenciasDAO dao = new ExistenciasDAO();
            
            if (dao.eliminar(idEliminar)) {
                actualizarTabla(); 
                
                btnLimpiarActionPerformed(null);
                JOptionPane.showMessageDialog(this, "Registro eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el registro en la base de datos.");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: El ID seleccionado no es un número válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    try {
        if (txtIdProducto1.getText().isEmpty() || txtNombreProducto.getText().isEmpty() || txtBodegaId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete los campos obligatorios (ID Producto, Nombre y Bodega).");
            return;
        }

        Controlador.Logistica.clsExistencias nuevaExistencia = new Controlador.Logistica.clsExistencias();
        
        nuevaExistencia.setProdid(Integer.parseInt(txtIdProducto1.getText()));
        nuevaExistencia.setExnombreproducto(txtNombreProducto.getText());
        nuevaExistencia.setExistock(Integer.parseInt(txtStockActual.getText()));
        nuevaExistencia.setBodegaid(Integer.parseInt(txtBodegaId.getText()));
        nuevaExistencia.setExmarca(txtMarcaPedido.getText());
        nuevaExistencia.setExlinea(txtLineaPedido.getText());

        ExistenciasDAO dao = new ExistenciasDAO();
        
        if (dao.insertar(nuevaExistencia)) {
            actualizarTabla();    
            JOptionPane.showMessageDialog(this, "Registro guardado exitosamente en la base de datos.");      
            btnLimpiarActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar en la base de datos.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: Asegúrese de ingresar números válidos en ID, Stock y Bodega.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
try {
        // Validamos que el ID no esté vacío
        if (txtIdExistencias.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro de la tabla para modificar.");
            return;
        }

        Controlador.Logistica.clsExistencias modExistencia = new Controlador.Logistica.clsExistencias();
        
        
        modExistencia.setExistenciaid(Integer.parseInt(txtIdExistencias.getText())); 
        modExistencia.setProdid(Integer.parseInt(txtIdProducto1.getText()));
        modExistencia.setExnombreproducto(txtNombreProducto.getText());
        modExistencia.setExistock(Integer.parseInt(txtStockActual.getText()));
        modExistencia.setBodegaid(Integer.parseInt(txtBodegaId.getText()));
        modExistencia.setExmarca(txtMarcaPedido.getText());
        modExistencia.setExlinea(txtLineaPedido.getText());

        ExistenciasDAO dao = new ExistenciasDAO();
        if (dao.actualizar(modExistencia)) {

            actualizarTabla(); 
            
            JOptionPane.showMessageDialog(this, "¡Registro actualizado con éxito!");
            btnLimpiarActionPerformed(null); 
            txtIdExistencias.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error: No se pudo actualizar en la base de datos.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error técnico: " + e.getMessage());
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtIdExistencias.setText("");
        txtNombreProducto.setText("");
        txtStockActual.setText("");
       txtBodegaId.setText("");
       txtBodegaId.setText("");
        txtMarcaPedido.setText("");
        txtLineaPedido.setText("");
        txtBuscar.setText("");
        tablaStock.clearSelection();
        cboxTipoBusqueda.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        Vista.Logistica.frmReportes ventana = new Vista.Logistica.frmReportes();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void txtBodegaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodegaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBodegaIdActionPerformed

    private void txtIdExistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdExistenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdExistenciasActionPerformed

    private void tablaStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaStockMouseClicked
        if (evt.getClickCount() == 2) {
        
        int filaVisual = tablaStock.getSelectedRow();
        
        if (filaVisual != -1) {
            int filaModelo = tablaStock.convertRowIndexToModel(filaVisual);
            
            txtIdExistencias.setText(modeloStock.getValueAt(filaModelo, 0).toString());
            txtIdProducto1.setText(modeloStock.getValueAt(filaModelo, 1).toString());
            txtNombreProducto.setText(modeloStock.getValueAt(filaModelo, 2).toString());
            txtStockActual.setText(modeloStock.getValueAt(filaModelo, 3).toString());
            txtBodegaId.setText(modeloStock.getValueAt(filaModelo, 4).toString());
            txtMarcaPedido.setText(modeloStock.getValueAt(filaModelo, 5).toString());
            txtLineaPedido.setText(modeloStock.getValueAt(filaModelo, 6).toString());
 
            txtIdExistencias.setEditable(false);
            txtIdExistencias.setEnabled(false); 
        }
    }
    }//GEN-LAST:event_tablaStockMouseClicked
private void buscarPorIDS() {
        System.out.println("Buscando por ID en la BD...");
    }
private void buscarPorMarca() {
    System.out.println("Buscando por Marca en Stock...");
}

private void buscarPorLinea() {
    System.out.println("Buscando por Línea en Stock...");
}

    private void buscarPorNombreS() {
        System.out.println("Buscando por Tipo (Entrada/Salida)...");
    }

  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMantenimientoStock().setVisible(true));
    }
    
    
    private void cargarDatosEjemplo() {
    modeloStock.addRow(new Object[]{"P001", "Martillo Pro", "50", "Unidades"});
    modeloStock.addRow(new Object[]{"P002", "Clavos 2 pulg", "500", "Bolsas"});
}
    
    

    
   
public void actualizarTabla() {
    // 1. Limpiar la tabla visual para no duplicar datos
    modeloStock.setRowCount(0);

    // 2. Instanciar el DAO y obtener la lista real de la base de datos
    ExistenciasDAO dao = new ExistenciasDAO();
    List<Controlador.Logistica.clsExistencias> listaExistencias = dao.listar();

    // 3. Llenar el modelo de la tabla con los datos reales
    for (Controlador.Logistica.clsExistencias existencia : listaExistencias) {
        Object[] fila = {
            existencia.getExistenciaid(), // Aquí aparecerá el ID real de SQL
            existencia.getProdid(),
            existencia.getExnombreproducto(),
            existencia.getExistock(),
            existencia.getBodegaid(),
            existencia.getExmarca(),
            existencia.getExlinea()
        };
        modeloStock.addRow(fila);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAdyda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> cboxTipoBusqueda;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label19;
    private javax.swing.JLabel label21;
    private javax.swing.JTable tablaStock;
    private javax.swing.JTextField txtBodegaId;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdExistencias;
    private javax.swing.JTextField txtIdProducto1;
    private javax.swing.JTextField txtLineaPedido;
    private javax.swing.JTextField txtMarcaPedido;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtStockActual;
    // End of variables declaration//GEN-END:variables
}
