/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 24-04-2026  1. Creacion frmMantenimientoKardex, implementaciones basicas
                              //09-05-2026  2. Implementacion de funcionalidad de botones
                              //11-05-2026  3. Implementacion Marca y Linea
                              //13-05-2023  4. Implementacion CRUD
                              //14-05-2026  5. Implementacion con bitacora 
                              //15-05-2026  6. Mantenimiento general
                              
package Vista.Logistica;
import Controlador.clsUsuarioConectado;
import Modelo.PermisosDAO;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author macoh
 */
public class frmMantenimientoKardex extends javax.swing.JInternalFrame {
    private javax.swing.table.DefaultTableModel modeloKardex;
    private Modelo.Logistica.MovimientosInventarioDAO daoKardex = new Modelo.Logistica.MovimientosInventarioDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMantenimientoKardex.class.getName());

    /**
     * Creates new form frmMantenimientoKardex
     */
    
  

    public frmMantenimientoKardex() {
      initComponents();
      cargarPermisos(); 
      
       modeloKardex = new javax.swing.table.DefaultTableModel(
        new Object [][] {}, 
        new String [] { 
            "ID Movimiento", "Tipo de Movimiento", "Producto", 
            "Motivo Movimiento", "BodegaId", "Fecha", 
            "Cantidad", "Marca", "Linea" 
        }
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };
    tablaKardex.setModel(modeloKardex);
    txtIdMovimiento.setEditable(false);
    txtIdMovimiento.setEnabled(false);
    cargarDatosTablaKardex();
    this.setClosable(true);
    this.setIconifiable(true);
    this.setMaximizable(true);
    this.setResizable(true);
}
    public void cargarPermisos() {
        int usuId = clsUsuarioConectado.getUsuId();
        PermisosDAO permisosDAO = new PermisosDAO();

        // 2001 es el código de la aplicación Mantenimiento Kardex
        int codigoAplicacion = 2001; 

        btnBuscar.setEnabled(true); // Para consulta su puso directo en true
        
       
     /*  // Si más adelante agregas más botones a este formulario, puedes usar esto:
     
        btnRegistrar.setEnabled(permisosDAO.puedeInsertar(usuId, codigoAplicacion));
        btnModificar.setEnabled(permisosDAO.puedeModificar(usuId, codigoAplicacion));
        btnEliminar.setEnabled(permisosDAO.puedeEliminar(usuId, codigoAplicacion));
        btnReportes.setEnabled(permisosDAO.puedeReportar(usuId, codigoAplicacion));
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaKardex = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboxTipoBusqueda = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        txtTipoMovimiento = new javax.swing.JTextField();
        label21 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        label16 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        txtMarcaPedido = new javax.swing.JTextField();
        txtLineaPedido = new javax.swing.JTextField();
        label14 = new javax.swing.JLabel();
        label17 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        label15 = new javax.swing.JLabel();
        txtIdMovimiento = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        label13 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        txtBodega = new javax.swing.JTextField();
        label22 = new javax.swing.JLabel();
        label23 = new javax.swing.JLabel();
        txtMotivoMovimiento = new javax.swing.JTextField();
        label19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tablaKardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Movimiento", "Tipo de Movimiento", "Producto", "Motivo Moviemiento", "BodegaId", "Fecha", "Cantidad", "Marca", "Linea"
            }
        ));
        tablaKardex.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaKardexAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaKardex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaKardexMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaKardex);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Kardex Invetarios");

        cboxTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Movimiento", "Tipo de Movimiento", "Producto", "Motivo Movimiento", "Bodega ID", "Fecha", "Marca", "Linea" }));
        cboxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoBusquedaActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 227, 250));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        txtTipoMovimiento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTipoMovimiento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label21.setText("Tipo Moviemiento");

        txtCantidad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        label16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label16.setText("ID Marca");

        label12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label12.setText("Cantidad");

        txtMarcaPedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtMarcaPedido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtLineaPedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtLineaPedido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label14.setText("ID Producto");

        label17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label17.setText("ID Linea");

        txtProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label15.setText("ID Movimiento");

        txtIdMovimiento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdMovimiento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtFecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFecha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        label13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label13.setText("Fecha");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        txtBodega.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtBodega.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label22.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label22.setText("Motivo Movimiento");

        label23.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label23.setText("ID Bodega");

        txtMotivoMovimiento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtMotivoMovimiento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label19.setText("*Dar doble click a la fila deseada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label19)
                                .addGap(352, 352, 352)
                                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(label21)
                                                    .addComponent(label15)
                                                    .addComponent(label14))
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label23)
                                            .addGap(61, 61, 61)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMotivoMovimiento)
                                            .addComponent(txtIdMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                            .addComponent(txtTipoMovimiento)
                                            .addComponent(txtProducto)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtLineaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtMarcaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label13)
                                            .addGap(41, 41, 41)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(37, 37, 37))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cboxTipoBusqueda, 0, 0, Short.MAX_VALUE)
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscar)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(cboxTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label15)
                            .addComponent(txtIdMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label21)
                            .addComponent(txtTipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label14)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label22)
                            .addComponent(txtMotivoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label23)
                            .addComponent(txtBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar)
                            .addComponent(btnModificar)
                            .addComponent(btnRegistrar)
                            .addComponent(btnEliminar)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label12)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarcaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label17)
                            .addComponent(txtLineaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReportes)
                            .addComponent(btnAyuda)
                            .addComponent(label19))))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
  txtIdMovimiento.setText("");
    txtTipoMovimiento.setText("");
    txtProducto.setText("");
    txtMotivoMovimiento.setText(""); // Agregado
    txtBodega.setText("");           // Agregado
    txtFecha.setText("");
    txtCantidad.setText("");
    txtMarcaPedido.setText("");
    txtLineaPedido.setText("");
    txtBuscar.setText("");
    tablaKardex.clearSelection();
    cboxTipoBusqueda.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tablaKardexAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaKardexAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaKardexAncestorAdded

    private void cboxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoBusquedaActionPerformed
 txtBuscar.setText("");
    txtBuscar.requestFocus();
    TableRowSorter<DefaultTableModel> sorter = (TableRowSorter<DefaultTableModel>) tablaKardex.getRowSorter();
    if (sorter != null) {
        sorter.setRowFilter(null);
    }
    }//GEN-LAST:event_cboxTipoBusquedaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        String filtro = txtBuscar.getText().trim().toLowerCase();
    String criterio = cboxTipoBusqueda.getSelectedItem().toString();
    boolean encontrado = false;

    if (filtro.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor para buscar.");
        return;
    }
    int columna = 0;
    if (criterio.equals("ID Movimiento")) columna = 0;
    else if (criterio.equals("Tipo de Movimiento")) columna = 1;
    else if (criterio.equals("Producto")) columna = 2;
    else if (criterio.equals("Fecha")) columna = 3;


    for (int i = 0; i < tablaKardex.getRowCount(); i++) {
        String valorCelda = tablaKardex.getValueAt(i, columna).toString().toLowerCase();
        
        if (valorCelda.contains(filtro)) {
            tablaKardex.setRowSelectionInterval(i, i);
            encontrado = true;
            break; 
        }
    }

    if (!encontrado) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró coincidencia para: " + filtro);
    }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
  String filtro = txtBuscar.getText().trim();
    String criterio = cboxTipoBusqueda.getSelectedItem().toString();

    DefaultTableModel modelo = (DefaultTableModel) tablaKardex.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
    tablaKardex.setRowSorter(sorter);

    if (filtro.isEmpty()) {
        sorter.setRowFilter(null);
    } else {
        int indiceColumna = 0;
        
        switch (criterio) {
            case "ID Movimiento":      indiceColumna = 0; break;
            case "Tipo de Movimiento": indiceColumna = 1; break;
            case "Producto":           indiceColumna = 2; break;
            case "Motivo Movimiento":  indiceColumna = 3; break;
            case "Bodega ID":          indiceColumna = 4; break;
            case "Fecha":              indiceColumna = 5; break;
            case "Cantidad":           indiceColumna = 6; break;
            case "Marca":              indiceColumna = 7; break; 
            case "Linea":              indiceColumna = 8; break; 
            default:                   indiceColumna = 0; break;
        }

        try {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro, indiceColumna));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en el filtro: " + e.getMessage());
        }
    
    }
        
        //     BitacoraDAO bitacoraDAO = new BitacoraDAO();
        //    bitacoraDAO.insert(idUsuario, Aplcodigo, "CONSULTA");    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Vista.Logistica.frmAyuda ventanaAyuda = new Vista.Logistica.frmAyuda();
    
    ventanaAyuda.setVisible(true);
    ventanaAyuda.setLocationRelativeTo(null);
    //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        try {
        String ruta = "C:\\Users\\ferit\\Desktop\\proyFinalP32K26b\\proyectop32k26b\\proyectop32k26b\\src\\main\\java\\Ayudas\\Logistica\\Logistica.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (txtIdMovimiento.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe dar doble clic al registro de la tabla que desea eliminar.");
            return;
        }
        int respuesta = JOptionPane.showConfirmDialog(this, 
                "¿Seguro que desea eliminar este registro de la Base de Datos?", 
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                int idAEliminar = Integer.parseInt(txtIdMovimiento.getText().trim());
                if (daoKardex.eliminar(idAEliminar)) {
                  

                    int filaModelo = -1;
                    for (int i = 0; i < modeloKardex.getRowCount(); i++) {
                        if (modeloKardex.getValueAt(i, 0).toString().equals(String.valueOf(idAEliminar))) {
                            filaModelo = i;
                            break;
                        }
                    }
                    if (filaModelo != -1) {
                        modeloKardex.removeRow(filaModelo);
                    }

                    JOptionPane.showMessageDialog(this, "Registro eliminado correctamente.");
                    btnActualizarActionPerformed(null);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Error: No se pudo eliminar el registro en la base de datos.");
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error: El ID del movimiento no es un número válido.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
try {
            Controlador.Logistica.clsMovimientosInventario mov = new Controlador.Logistica.clsMovimientosInventario();
            mov.setProdid(Integer.parseInt(txtProducto.getText().trim()));
            mov.setBodegaid(Integer.parseInt(txtBodega.getText().trim()));
            mov.setMovtipomovimiento(txtTipoMovimiento.getText().trim());
            mov.setMovmotivo(txtMotivoMovimiento.getText().trim());
            mov.setMovcantidad(Integer.parseInt(txtCantidad.getText().trim()));
            mov.setMovmarca(txtMarcaPedido.getText().trim());
            mov.setMovlinea(txtLineaPedido.getText().trim());
            
            mov.setMovfecha(new java.sql.Timestamp(System.currentTimeMillis()));

            if (daoKardex.insertar(mov)) {
                cargarDatosTablaKardex();

                JOptionPane.showMessageDialog(this, "Movimiento registrado y guardado en Bitácora.");
                btnActualizarActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se pudo guardar en la base de datos.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Producto, Bodega y Cantidad deben ser números.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

  try {
            if (txtIdMovimiento.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un registro de la tabla para modificar.");
                return;
            }
            Controlador.Logistica.clsMovimientosInventario modKardex = new Controlador.Logistica.clsMovimientosInventario();
            
            modKardex.setMovimientoid(Integer.parseInt(txtIdMovimiento.getText().trim())); 
            modKardex.setMovtipomovimiento(txtTipoMovimiento.getText().trim());
            modKardex.setProdid(Integer.parseInt(txtProducto.getText().trim())); 
            modKardex.setMovmotivo(txtMotivoMovimiento.getText().trim());
            modKardex.setBodegaid(Integer.parseInt(txtBodega.getText().trim())); 
            modKardex.setMovcantidad(Integer.parseInt(txtCantidad.getText().trim()));
            modKardex.setMovmarca(txtMarcaPedido.getText().trim());
            modKardex.setMovlinea(txtLineaPedido.getText().trim());
            modKardex.setMovfecha(java.sql.Timestamp.valueOf(txtFecha.getText().trim()));


            if (daoKardex.actualizar(modKardex)) {
                cargarDatosTablaKardex(); 
                
                JOptionPane.showMessageDialog(this, "¡Registro de Kardex actualizado con éxito!");            
                btnActualizarActionPerformed(null); 
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se pudo actualizar en la base de datos.");
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Error: Asegúrate de que los campos numéricos (ID, Producto, Bodega, Cantidad) tengan formatos válidos.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error técnico: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        Vista.Logistica.frmReportes ventana = new Vista.Logistica.frmReportes();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReportesActionPerformed

  
    
    
    
    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (tablaKardex.getRowSorter() != null) {
            tablaKardex.setRowSorter(null); 
        }
        txtBuscar.setText("");
        cboxTipoBusqueda.setSelectedIndex(0);
        txtIdMovimiento.setText("");
        txtTipoMovimiento.setText("");
        txtProducto.setText("");
        txtMotivoMovimiento.setText("");
        txtBodega.setText("");
        txtFecha.setText("");
        txtCantidad.setText("");
        txtMarcaPedido.setText("");
        txtLineaPedido.setText("");
        txtIdMovimiento.setEditable(true);
        tablaKardex.clearSelection();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablaKardexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaKardexMouseClicked
       if (evt.getClickCount() == 2) { 
        int filaVisual = tablaKardex.getSelectedRow();
        
        if (filaVisual != -1) {
            try {
                int filaModelo = tablaKardex.convertRowIndexToModel(filaVisual);
                txtIdMovimiento.setText(obtenerValor(modeloKardex.getValueAt(filaModelo, 0)));
                txtTipoMovimiento.setText(obtenerValor(modeloKardex.getValueAt(filaModelo, 1)));
                txtProducto.setText(obtenerValor(modeloKardex.getValueAt(filaModelo, 2)));
                txtMotivoMovimiento.setText(obtenerValor(modeloKardex.getValueAt(filaModelo, 3)));
                txtBodega.setText(obtenerValor(modeloKardex.getValueAt(filaModelo, 4)));
                txtFecha.setText(obtenerValor(modeloKardex.getValueAt(filaModelo, 5)));
                txtCantidad.setText(obtenerValor(modeloKardex.getValueAt(filaModelo, 6)));
                txtMarcaPedido.setText(obtenerValor(modeloKardex.getValueAt(filaModelo, 7)));
                txtLineaPedido.setText(obtenerValor(modeloKardex.getValueAt(filaModelo, 8)));
                txtIdMovimiento.setEditable(false);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al capturar datos: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_tablaKardexMouseClicked
private void buscarPorIDk() {
        System.out.println("Buscando por ID en la BD...");
    }

    private void buscarPorMovimiento() {
        System.out.println("Buscando por Tipo (Entrada/Salida)...");
    }

    private void buscarPorProducto() {
        System.out.println("Buscando por nombre de Producto...");
    }

    private void buscarPorFechak() {
        System.out.println("Buscando por Fecha...");
    }
     private void buscarPorMarca() {
        System.out.println("Buscando por Marca...");
    }
      private void buscarPorLinea() {
        System.out.println("Buscando por Linea...");
    }
      private void buscarPorMotivo() {
        System.out.println("Buscando por Linea...");
    }
      private void buscarPorBodega() {
        System.out.println("Buscando por Linea...");
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMantenimientoKardex().setVisible(true));
    }


public void registrarMovimientoExterno(Object[] fila) {
    if (fila.length == 9) { 
        modeloKardex.addRow(fila);
    } else {
        System.out.println("Error: El movimiento requiere 9 columnas.");
    }
}


    private String obtenerValor(Object objeto) {
        return (objeto != null) ? objeto.toString() : "";
}

private void cargarDatosTablaKardex() {
   modeloKardex.setRowCount(0);
        try {
            java.util.List<Controlador.Logistica.clsMovimientosInventario> lista = daoKardex.listar();
            
            if (lista != null) {
                for (Controlador.Logistica.clsMovimientosInventario mov : lista) {
                    Object[] fila = {
                        mov.getMovimientoid(),
                        mov.getMovtipomovimiento(),
                        mov.getProdid(),
                        mov.getMovmotivo(),
                        mov.getBodegaid(),
                        mov.getMovfecha(),
                        mov.getMovcantidad(),
                        mov.getMovmarca(),
                        mov.getMovlinea()
                    };
                    modeloKardex.addRow(fila); 
                }
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al cargar datos desde la Base de Datos: " + e.getMessage(), 
                "Error del Sistema", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> cboxTipoBusqueda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label19;
    private javax.swing.JLabel label21;
    private javax.swing.JLabel label22;
    private javax.swing.JLabel label23;
    private javax.swing.JTable tablaKardex;
    private javax.swing.JTextField txtBodega;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdMovimiento;
    private javax.swing.JTextField txtLineaPedido;
    private javax.swing.JTextField txtMarcaPedido;
    private javax.swing.JTextField txtMotivoMovimiento;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtTipoMovimiento;
    // End of variables declaration//GEN-END:variables
}
