/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 24-04-2026  1. Creacion frmMantenimientoTransporte, implementaciones basicas
                              //09-05-2026  2. Implementacion de funcionalidad de botones
                              //13-05-2023  4. Implementacion CRUD
                              //14-05-2026  5. Implementacion con metodo de bitacora 
                              //15-05-2026  6. Mantenimiento general

package Vista.Logistica;

import Controlador.clsUsuarioConectado;
import Modelo.PermisosDAO;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import Controlador.Logistica.clsTransportistas;
import Modelo.BitacoraDAO;
import Modelo.Logistica.TransportistasDAO;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

/**
 *
 * @author macoh
 */
public class frmMantenimientoTransporte extends javax.swing.JInternalFrame {
private DefaultTableModel modeloTransportes;

    public frmMantenimientoTransporte() {
        initComponents();
        
        txtIdtransporte.setEditable(false);
       
    txtIdtransporte.setEnabled(false);  
      modeloTransportes = new DefaultTableModel(
            new Object[]{"ID Transporte", "ID Empleado", "Tipo Vehículo"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tablaTransporte.setModel(modeloTransportes);
        actualizarTabla();
        cargarPermisos();
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        
    }
    public void cargarPermisos() {
        int usuId = clsUsuarioConectado.getUsuId();
        PermisosDAO permisosDAO = new PermisosDAO();
        int codigoAplicacion = 2000; 
        btnBuscar.setEnabled(permisosDAO.puedeBuscar(usuId, codigoAplicacion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTransporte = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboxTipoBusqueda = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        label15 = new javax.swing.JLabel();
        txtTipoVehiculo = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        label16 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        label17 = new javax.swing.JLabel();
        txtIdtransporte = new javax.swing.JTextField();
        label19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(782, 736));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        tablaTransporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transporte", "ID empldeado", "Tipo de Vehiculo"
            }
        ));
        tablaTransporte.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaTransporteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaTransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTransporteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaTransporte);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 310, 692, 300);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Transportistas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 20, 160, 25);

        cboxTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Trasnsporte", "ID Empleado", "Tipo de Vehiculo" }));
        cboxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cboxTipoBusqueda);
        cboxTipoBusqueda.setBounds(10, 30, 139, 26);

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar);
        txtBuscar.setBounds(10, 70, 110, 26);

        btnBuscar.setBackground(new java.awt.Color(255, 227, 250));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(130, 70, 72, 27);

        label15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label15.setText("Tipo Vehiculo");
        getContentPane().add(label15);
        label15.setBounds(20, 220, 84, 16);

        txtTipoVehiculo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTipoVehiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtTipoVehiculo);
        txtTipoVehiculo.setBounds(120, 220, 170, 17);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(430, 140, 90, 30);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(430, 170, 90, 30);

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAyuda);
        btnAyuda.setBounds(600, 220, 72, 23);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(340, 200, 90, 23);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(340, 140, 90, 23);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(340, 170, 90, 23);

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes);
        btnReportes.setBounds(520, 220, 76, 23);

        label16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label16.setText("ID Transporte");
        getContentPane().add(label16);
        label16.setBounds(20, 140, 80, 16);

        txtIdEmpleado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdEmpleado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtIdEmpleado);
        txtIdEmpleado.setBounds(120, 180, 170, 17);

        label17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label17.setText("ID Empleado");
        getContentPane().add(label17);
        label17.setBounds(20, 180, 90, 16);

        txtIdtransporte.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdtransporte.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtIdtransporte);
        txtIdtransporte.setBounds(120, 140, 170, 17);

        label19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label19.setText("*Dar doble click a la fila deseada");
        getContentPane().add(label19);
        label19.setBounds(10, 280, 196, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaTransporteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaTransporteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaTransporteAncestorAdded

    private void cboxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoBusquedaActionPerformed

        txtBuscar.setText("");
        txtBuscar.requestFocus();
        String seleccion = cboxTipoBusqueda.getSelectedItem().toString();
        switch (seleccion) {
            case "ID Movimiento":
            buscarPorID();
            break;
            case "Tipo de Movimiento":
            buscarPorNombre();
            break;
            case "Producto":
            buscarPorTipoVehiculo();
            break;
   
        }
    }//GEN-LAST:event_cboxTipoBusquedaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        String filtro = txtBuscar.getText().trim().toLowerCase();
        String criterio = cboxTipoBusqueda.getSelectedItem().toString();
        boolean encontrado = false;

        if (filtro.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor para buscar.");
            return;
        }
        int columna = 0;
        if (criterio.equals("ID Movimiento")) columna = 0;
        else if (criterio.equals("Tipo de Movimiento")) columna = 1;
        else if (criterio.equals("Producto")) columna = 2;
        else if (criterio.equals("Fecha")) columna = 3;

        for (int i = 0; i < tablaTransporte.getRowCount(); i++) {
            String valorCelda = tablaTransporte.getValueAt(i, columna).toString().toLowerCase();

            if (valorCelda.contains(filtro)) {
                tablaTransporte.setRowSelectionInterval(i, i);
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró coincidencia para: " + filtro);
        }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
String filtro = txtBuscar.getText().trim();

TableRowSorter<DefaultTableModel> sorter =
        new TableRowSorter<>(
                (DefaultTableModel) tablaTransporte.getModel()
        );

tablaTransporte.setRowSorter(sorter);

if (filtro.length() == 0) {

    sorter.setRowFilter(null);

} else {

    int seleccion = cboxTipoBusqueda.getSelectedIndex();
    int indiceColumna = 0;

    if (seleccion == 0) {

        indiceColumna = 0;

    } else if (seleccion == 1) {

        indiceColumna = 1;

    } else if (seleccion == 2) {

        indiceColumna = 2;

    } else {

        indiceColumna = 0;
    }

    try {

        sorter.setRowFilter(
                RowFilter.regexFilter(
                        "(?i)" + filtro,
                        indiceColumna
                )
        );

        if (tablaTransporte.getRowCount() == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "No se encontraron resultados."
            );
        }

        // ================= BITACORA =================

        try {

            int idUsuario =
                    clsUsuarioConectado.getUsuId();

            int aplCodigo = 2000;

            BitacoraDAO bitacoraDAO =
                    new BitacoraDAO();

            bitacoraDAO.insert(
                    idUsuario,
                    aplCodigo,
                    "Consulta transportista ID " + filtro
            );

        } catch (Exception ex) {

            System.out.println(
                    "Error bitácora consulta: "
                    + ex.getMessage()
            );
        }

        // ============================================

    } catch (Exception e) {

        System.err.println(
                "Error en el filtro: "
                + e.getMessage()
        );
    }
}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
      txtTipoVehiculo.setText("");
    txtIdEmpleado.setText("");
    txtIdtransporte.setText("");
    txtIdtransporte.setEditable(false);
    txtIdtransporte.setEnabled(false);   
    tablaTransporte.clearSelection();
    cboxTipoBusqueda.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

       if (tablaTransporte.getRowSorter() != null) {
        tablaTransporte.setRowSorter(null);
    }
    txtBuscar.setText("");
    cboxTipoBusqueda.setSelectedIndex(0);

    txtTipoVehiculo.setText("");
    txtIdtransporte.setText("");
    txtIdEmpleado.setText("");
    txtIdtransporte.setEditable(false); 
    tablaTransporte.clearSelection();
    actualizarTabla(); 

    JOptionPane.showMessageDialog(this, "Formulario e interfaz restablecidos correctamente.");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Vista.Logistica.frmAyuda ventanaAyuda = new Vista.Logistica.frmAyuda();

        ventanaAyuda.setVisible(true);
        ventanaAyuda.setLocationRelativeTo(null);
        //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        try {
        String ruta = "C:\\Users\\ferit\\Desktop\\proyFinalP32K26b\\proyectop32k26b\\proyectop32k26b\\src\\main\\java\\Ayudas\\Logistica\\Logistica.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
int filaVisual = tablaTransporte.getSelectedRow();

    if (filaVisual != -1) {
        int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar este transportista de la Base de Datos?",
            "Confirmación de eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                int idAEliminar = Integer.parseInt(tablaTransporte.getValueAt(filaVisual, 0).toString());
                Modelo.Logistica.TransportistasDAO dao = new Modelo.Logistica.TransportistasDAO();

                if (dao.eliminar(idAEliminar)) {
                    int filaModelo = tablaTransporte.convertRowIndexToModel(filaVisual);
                    modeloTransportes.removeRow(filaModelo);

                    btnLimpiarActionPerformed(null);
                    JOptionPane.showMessageDialog(this, "Registro eliminado de la base de datos correctamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Error: El registro no pudo ser eliminado en MySQL.");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al procesar la eliminación: " + e.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila de la tabla para eliminar.");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
if (txtIdEmpleado.getText().trim().isEmpty() || 
    txtTipoVehiculo.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(this,
        "Complete los campos obligatorios (ID Empleado y Tipo Vehículo).");
    return;
}

try {

    Controlador.Logistica.clsTransportistas transportista =
            new Controlador.Logistica.clsTransportistas();

    transportista.setEmpcodigo(
            Integer.parseInt(txtIdEmpleado.getText().trim()));

    transportista.setTrantipovehiculo(
            txtTipoVehiculo.getText().trim());

    Modelo.Logistica.TransportistasDAO dao =
            new Modelo.Logistica.TransportistasDAO();

    if (dao.insertar(transportista)) {

        JOptionPane.showMessageDialog(this,
                "Transportista registrado con éxito.");

        actualizarTabla();

        btnLimpiarActionPerformed(null);

    } else {

        JOptionPane.showMessageDialog(this,
                "No se pudo registrar el transportista.");
    }

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(this,
            "El ID de empleado debe ser un número entero válido.");
}
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
if (txtIdtransporte.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(this,
        "Debe seleccionar un registro dando doble clic en la tabla para modificar.");

    return;
}

try {

    int idTransportista =
            Integer.parseInt(txtIdtransporte.getText().trim());

    String nuevoVehiculo =
            txtTipoVehiculo.getText().trim();

    String empIdStr =
            txtIdEmpleado.getText().trim();

    if (nuevoVehiculo.isEmpty() || empIdStr.isEmpty()) {

        JOptionPane.showMessageDialog(this,
            "Los campos no pueden estar vacíos para modificar.");

        return;
    }

    Controlador.Logistica.clsTransportistas obj =
            new Controlador.Logistica.clsTransportistas();

    obj.setTranid(idTransportista);

    obj.setTrantipovehiculo(nuevoVehiculo);

    obj.setEmpcodigo(Integer.parseInt(empIdStr));

    Modelo.Logistica.TransportistasDAO dao =
            new Modelo.Logistica.TransportistasDAO();

    if (dao.actualizar(obj)) {

        actualizarTabla();

        JOptionPane.showMessageDialog(this,
                "Registro actualizado exitosamente.");

        btnLimpiarActionPerformed(null);

    } else {

        JOptionPane.showMessageDialog(this,
                "Error: No se pudo actualizar en la base de datos.");
    }

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(this,
            "El ID de empleado debe ser numérico.");

} catch (Exception e) {

    JOptionPane.showMessageDialog(this,
            "Error inesperado: " + e.getMessage());
}
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        Vista.Logistica.frmReportes ventana = new Vista.Logistica.frmReportes();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void tablaTransporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTransporteMouseClicked

    if (evt.getClickCount() == 2) { 
        int filaVisual = tablaTransporte.getSelectedRow();
        
        if (filaVisual != -1) {
            try {
                int filaModelo = tablaTransporte.convertRowIndexToModel(filaVisual);
                txtIdtransporte.setText(modeloTransportes.getValueAt(filaModelo, 0).toString());
                txtIdEmpleado.setText(modeloTransportes.getValueAt(filaModelo, 1).toString());
                txtTipoVehiculo.setText(modeloTransportes.getValueAt(filaModelo, 2).toString());
                txtIdtransporte.setEditable(false);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al capturar los datos de la tabla: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_tablaTransporteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMantenimientoTransporte().setVisible(true));
    }
    
    
    private void buscarPorID() {
        System.out.println("Buscando por ID...");
      
    }

    private void buscarPorNombre() {
        System.out.println("Buscando por Nombre...");
    }

    private void buscarPorTipoVehiculo() {
        System.out.println("Buscando por Vehiculo...");
    }

  
    
   public void actualizarTabla() {
    Modelo.Logistica.TransportistasDAO transporteDAO = new Modelo.Logistica.TransportistasDAO();
    List<Controlador.Logistica.clsTransportistas> lista = transporteDAO.listar();

    modeloTransportes.setRowCount(0); 

    for (Controlador.Logistica.clsTransportistas t : lista) {
        modeloTransportes.addRow(new Object[]{
            t.getTranid(),    
            t.getEmpcodigo(), 
            t.getTrantipovehiculo()  
        });
    }
}
   
 
  
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> cboxTipoBusqueda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label19;
    private javax.swing.JTable tablaTransporte;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdtransporte;
    private javax.swing.JTextField txtTipoVehiculo;
    // End of variables declaration//GEN-END:variables
}
