/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 24-04-2026  1. Creacion frmMantenimientPedidos, implementaciones basicas
                              //09-05-2026  2. Corregido, funcionalidad de botnoes --Falta Reportes--
                              //09-05-2026  3. Implementacion, boton ayuda  
                              //11-05-2026  4. Implementacion Marca y Linea
                              //14-05-2026  5. Implementacion con bitacora 
                              //15-05-2026  6. Mantenimiento general
package Vista.Logistica;
import java.io.File;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author macoh
 */
public class frmMantenimientoPedidos extends javax.swing.JInternalFrame  {
  javax.swing.table.DefaultTableModel modeloLocal;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMantenimientoPedidos.class.getName());

    public frmMantenimientoPedidos() {
        initComponents();
        String[] titulos = {"ID Pedido","ID Cliente", "Estado Pedido", "Producto ID", "Cantidad", "Marca", "Linea"};
        modeloLocal = new javax.swing.table.DefaultTableModel(null, titulos);
        tablaUsuarios1.setModel(modeloLocal);
        cargarPermisos();
        
        txtIdpedidos.setEditable(false);
    txtIdpedidos.setEnabled(false);  
        
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        this.setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
        btnActualizar1ActionPerformed(null);
        
    }
    public void cargarPermisos() {
        // Obtener el ID del usuario conectado
        int usuId = Controlador.clsUsuarioConectado.getUsuId();
        Modelo.PermisosDAO permisosDAO = new Modelo.PermisosDAO();

        // Instrucciones para adaptarlo a otro formulario Cambiar el "2000" por el código de tu aplicación:
        //  Codigos de ejmplo utilizados de momento 2000 = Transportes | 2001 = Kardex | 2002 = Stock | 2003 = Pedidos
        int codigoAplicacion = 2003; 

        btnRegistrar1.setEnabled(permisosDAO.puedeInsertar(usuId, codigoAplicacion));
        btnBuscar1.setEnabled(permisosDAO.puedeBuscar(usuId, codigoAplicacion));
        btnModificar1.setEnabled(permisosDAO.puedeModificar(usuId, codigoAplicacion));
        btnEliminar1.setEnabled(permisosDAO.puedeEliminar(usuId, codigoAplicacion));
        btnReportes1.setEnabled(permisosDAO.puedeReportar(usuId, codigoAplicacion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        label10 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        label3 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtConfContraseña = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        label7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnReportes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        label5 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        label4 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        txtUltimaSesion = new javax.swing.JTextField();
        label6 = new javax.swing.JLabel();
        txtNombreReal = new javax.swing.JTextField();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtEstatus = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        label12 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        btnModificar1 = new javax.swing.JButton();
        txtProductoId = new javax.swing.JTextField();
        label15 = new javax.swing.JLabel();
        txtbuscado1 = new javax.swing.JTextField();
        txtIdpedidos = new javax.swing.JTextField();
        btnLimpiar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios1 = new javax.swing.JTable();
        btnReportes1 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        label19 = new javax.swing.JLabel();
        btnActualizar1 = new javax.swing.JButton();
        txtEstadoPedido = new javax.swing.JTextField();
        label21 = new javax.swing.JLabel();
        btnEliminar1 = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        label16 = new javax.swing.JLabel();
        txtMarcaPedido = new javax.swing.JTextField();
        txtLineaPedido = new javax.swing.JTextField();
        label17 = new javax.swing.JLabel();
        txtIdCliente1 = new javax.swing.JTextField();
        label18 = new javax.swing.JLabel();

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        label10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label10.setText("Telefono");

        label1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label1.setText("Usuarios");

        label11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label11.setText("Correo");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        txtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Nombre");

        label13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label13.setText("Direccion");

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtDireccion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtDireccion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtConfContraseña.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConfContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label7.setText("Conf. Contraseña");

        tablaUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Vendedor", "ID Empleado", "Correo", "Telefono", "Direccion", "Porcentaje", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        jLabel1.setText("Estatus: A = Activo     I = Inactivo\"");

        txtContrasena.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtContrasena.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("Contraseña");

        lb.setText(".");

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label4.setText("ID a buscar");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        txtUltimaSesion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtUltimaSesion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label6.setText("Ultima Sesion");

        txtNombreReal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombreReal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label8.setText("Nombre Real");

        label9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label9.setText("Estatus");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtEstatus.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtEstatus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtTelefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTelefono.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        label12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label12.setText("Cantidad");

        label2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label2.setText("Pedidos");

        label14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label14.setText("Producto ID");

        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        txtProductoId.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtProductoId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label15.setText("ID cliente");

        txtIdpedidos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdpedidos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtIdpedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdpedidosActionPerformed(evt);
            }
        });

        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        tablaUsuarios1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaUsuarios1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pedidos", "ID Cliente", "Estado Pedido", "ProductoID", "Cantidad", "Marca", "Linea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaUsuarios1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tablaUsuarios1);
        if (tablaUsuarios1.getColumnModel().getColumnCount() > 0) {
            tablaUsuarios1.getColumnModel().getColumn(0).setHeaderValue("ID Pedidos");
        }

        btnReportes1.setText("Reportes");
        btnReportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes1ActionPerformed(evt);
            }
        });

        lb1.setText(".");

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        label19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label19.setText("ID a buscar");

        btnActualizar1.setText("Actualizar");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        txtEstadoPedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtEstadoPedido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label21.setText("Estado Pedido");

        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnRegistrar1.setText("Registrar");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });

        txtCantidad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        label16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label16.setText("ID Marca");

        txtMarcaPedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtMarcaPedido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtLineaPedido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtLineaPedido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label17.setText("ID Linea");

        txtIdCliente1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdCliente1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label18.setText("ID pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbuscado1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(btnReportes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1019, Short.MAX_VALUE)
                .addComponent(btnActualizar1)
                .addGap(0, 125, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label21)
                            .addComponent(label14)
                            .addComponent(label12)
                            .addComponent(label15)
                            .addComponent(label16)
                            .addComponent(label17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdpedidos, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIdCliente1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstadoPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                                .addComponent(txtProductoId, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMarcaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLineaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb1)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdpedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label18))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label15)
                    .addComponent(txtIdCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label21)
                    .addComponent(txtEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label14)
                    .addComponent(txtProductoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label12)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarcaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLineaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar1)
                    .addComponent(btnEliminar1)
                    .addComponent(btnModificar1))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar1)
                    .addComponent(btnAyuda)
                    .addComponent(btnReportes1))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar1)
                    .addComponent(txtbuscado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label19))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar1)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

       

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //        // TODO add your handling code here:

      
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
      
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnReportesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
      
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
  String idBuscado = txtbuscado1.getText().trim();
    
    if(idBuscado.isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el ID del Pedido para buscar.");
        return;
    }

    boolean encontrado = false;
    for (int i = 0; i < modeloLocal.getRowCount(); i++) {
        if (modeloLocal.getValueAt(i, 0).toString().equals(idBuscado)) {
            txtIdpedidos.setText(modeloLocal.getValueAt(i, 0).toString());      // Columna 0: ID Pedido
            txtIdCliente1.setText(modeloLocal.getValueAt(i, 1).toString());     // Columna 1: ID Cliente (Te faltaba mapear este campo)
            txtEstadoPedido.setText(modeloLocal.getValueAt(i, 2).toString());   // Columna 2: Estado
            txtProductoId.setText(modeloLocal.getValueAt(i, 3).toString());     // Columna 3: Producto ID
            txtCantidad.setText(modeloLocal.getValueAt(i, 4).toString());       // Columna 4: Cantidad
            txtMarcaPedido.setText(modeloLocal.getValueAt(i, 5).toString());    // Columna 5: Marca
            txtLineaPedido.setText(modeloLocal.getValueAt(i, 6).toString());    // Columna 6: Linea
            
            tablaUsuarios1.setRowSelectionInterval(i, i);
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        JOptionPane.showMessageDialog(null, "No se encontró el pedido con ID: " + idBuscado);
    }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
                                             
int filaSeleccionada = tablaUsuarios1.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un pedido de la tabla para modificar.");
        return;
    }

    try {

        int idPedido = Integer.parseInt(txtIdpedidos.getText().trim());
        Controlador.Logistica.clsPedidos pedido = new Controlador.Logistica.clsPedidos();
        pedido.setPedid(idPedido);
        pedido.setCliid(Integer.parseInt(txtIdCliente1.getText().trim()));
        pedido.setPedestado(txtEstadoPedido.getText().trim());
        pedido.setProdid(Integer.parseInt(txtProductoId.getText().trim()));
        pedido.setPedcantidad(Integer.parseInt(txtCantidad.getText().trim()));
        pedido.setPedmarca(txtMarcaPedido.getText().trim());
        pedido.setPedlinea(txtLineaPedido.getText().trim());

        Modelo.Logistica.PedidosDAO dao = new Modelo.Logistica.PedidosDAO();
        
        if (dao.actualizar(pedido)) {
            modeloLocal.setValueAt(pedido.getPedid(), filaSeleccionada, 0);
            modeloLocal.setValueAt(pedido.getCliid(), filaSeleccionada, 1);
            modeloLocal.setValueAt(pedido.getPedestado(), filaSeleccionada, 2);
            modeloLocal.setValueAt(pedido.getProdid(), filaSeleccionada, 3);
            modeloLocal.setValueAt(pedido.getPedcantidad(), filaSeleccionada, 4);
            modeloLocal.setValueAt(pedido.getPedmarca(), filaSeleccionada, 5);
            modeloLocal.setValueAt(pedido.getPedlinea(), filaSeleccionada, 6);

            JOptionPane.showMessageDialog(null, "Registro #" + idPedido + " actualizado correctamente.");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar en la base de datos.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Asegúrese de que los campos ID, Cliente, Producto y Cantidad sean numéricos.");
    }
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
      
    limpiarCampos();
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void btnReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes1ActionPerformed
Vista.Logistica.frmReportes ventana = new Vista.Logistica.frmReportes();
    ventana.setVisible(true);
    ventana.setLocationRelativeTo(null);        
    }//GEN-LAST:event_btnReportes1ActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
           Vista.Logistica.frmAyuda ventanaAyuda = new Vista.Logistica.frmAyuda();
    
    ventanaAyuda.setVisible(true);
    ventanaAyuda.setLocationRelativeTo(null);
                                           
    //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        try {
        String ruta = "C:\\Users\\ferit\\Desktop\\proyFinalP32K26b\\proyectop32k26b\\proyectop32k26b\\src\\main\\java\\Ayudas\\Logistica\\Logistica.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
        }

    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
     try {
 
        modeloLocal.setRowCount(0); 
        Modelo.Logistica.PedidosDAO dao = new Modelo.Logistica.PedidosDAO();
        List<Controlador.Logistica.clsPedidos> lista = dao.listar(); 
        
        for (Controlador.Logistica.clsPedidos p : lista) {
            Object[] fila = {
                p.getPedid(),      
                p.getCliid(),       
                p.getPedestado(),   
                p.getProdid(),      
                p.getPedcantidad(),  
                p.getPedmarca(),    
                p.getPedlinea()      
            };
            modeloLocal.addRow(fila);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar la tabla: " + e.getMessage());
    }
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
   String idEliminar = txtIdpedidos.getText().trim();
    
    if(idEliminar.isEmpty()){
        JOptionPane.showMessageDialog(null, "Debe seleccionar un pedido o ingresar su ID para eliminar.");
        return;
    }

    int respuesta = JOptionPane.showConfirmDialog(null, 
        "¿Seguro que desea eliminar el pedido ID: " + idEliminar + "?", 
        "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        
    if (respuesta == JOptionPane.YES_OPTION) {
        try {
            int id = Integer.parseInt(idEliminar);
            Modelo.Logistica.PedidosDAO dao = new Modelo.Logistica.PedidosDAO();
            
            if (dao.eliminar(id)) {
                JOptionPane.showMessageDialog(null, "Pedido #" + id + " eliminado de la base de datos.");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID debe ser un número válido.");
        }
    
    }//GEN-LAST:event_btnEliminar1ActionPerformed

}
    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
    String idCli = txtIdCliente1.getText().trim(); 
    String estado = txtEstadoPedido.getText().trim();
    String producto = txtProductoId.getText().trim();
    String cantidad = txtCantidad.getText().trim();
    String marca = txtMarcaPedido.getText().trim(); 
    String linea = txtLineaPedido.getText().trim(); 

    if (idCli.isEmpty() || producto.isEmpty() || cantidad.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor llene los campos obligatorios (Cliente, Producto y Cantidad)");
        return;
    }

    try {
        Controlador.Logistica.clsPedidos pedido = new Controlador.Logistica.clsPedidos();
        
        pedido.setCliid(Integer.parseInt(idCli));
        pedido.setProdid(Integer.parseInt(producto));
        pedido.setPedcantidad(Integer.parseInt(cantidad));
        pedido.setPedmarca(marca);
        pedido.setPedlinea(linea);
        pedido.setPedestado(estado);
        
        Modelo.Logistica.PedidosDAO dao = new Modelo.Logistica.PedidosDAO();
        
        if (dao.insertar(pedido)) {
            
            JOptionPane.showMessageDialog(null, "Pedido registrado con éxito de forma automática.");
            limpiarCampos();
            
            btnActualizar1ActionPerformed(null); 
            
        } else {
            JOptionPane.showMessageDialog(null, "Error: No se pudo guardar en la base de datos.");
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Los campos Cliente, Producto y Cantidad deben ser números.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void tablaUsuarios1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaUsuarios1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaUsuarios1AncestorAdded

    private void txtIdpedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdpedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdpedidosActionPerformed

    public void limpiarCampos() {
  txtIdpedidos.setText("");      
        txtEstadoPedido.setText("");  
        txtProductoId.setText("");      
        txtCantidad.setText("");    
        txtbuscado1.setText("");
        txtMarcaPedido.setText("");
        txtLineaPedido.setText("");
}


    public void llenarTabla() {
  modeloLocal.setRowCount(0); 
        System.out.println("Vista: Solicitando datos a la base de datos...");
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMantenimientoPedidos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReportes1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label19;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label21;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTable tablaUsuarios1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtConfContraseña;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEstadoPedido;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtIdCliente1;
    private javax.swing.JTextField txtIdpedidos;
    private javax.swing.JTextField txtLineaPedido;
    private javax.swing.JTextField txtMarcaPedido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreReal;
    private javax.swing.JTextField txtProductoId;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUltimaSesion;
    private javax.swing.JTextField txtbuscado;
    private javax.swing.JTextField txtbuscado1;
    // End of variables declaration//GEN-END:variables
}
