/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 13-05-2026  1. Creacion frmMantenimientStock, implementaciones basicas
                              //13-05-2026  2. Implementacion de funcionalidad de botones
                              //13-05-2026  3. Implementacion Marca y Linea
                              //13-05-2023  4. Implementacion CRUD
                              //14-05-2026  5. Implementacion con bitacora 
                              //15-05-2026  6. Mantenimiento general



package Vista.Logistica;
import java.io.File; //para que se vea el archivo de ayuda llamado Logistica.chm
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author macoh
 */
public class frmMantenimientoBodega extends javax.swing.JInternalFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMantenimientoBodega.class.getName());
DefaultTableModel modeloBodega;
    /**
     * Creates new form frmMantenimientoBodega
     */
    public frmMantenimientoBodega() {
       initComponents();

        modeloBodega = (DefaultTableModel) tablaStock.getModel();
        tablaStock.setDefaultEditor(Object.class, null);
        
        txtIdBodega.setEditable(false);
    txtIdBodega.setEnabled(false); // Queda gris y protegido porque es autoincrementable
    
        cargarDatosTabla(); // L
        
  
         this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        this.setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdyda = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtNombreBodega = new javax.swing.JTextField();
        txtUbicacionBodega = new javax.swing.JTextField();
        label21 = new javax.swing.JLabel();
        label15 = new javax.swing.JLabel();
        txtIdBodega = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        label14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        cboxTipoBusqueda = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        label19 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);

        btnAdyda.setText("Ayuda");
        btnAdyda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdydaActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtNombreBodega.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombreBodega.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtUbicacionBodega.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtUbicacionBodega.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        label21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label21.setText("Bodega Nombre");

        label15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label15.setText("ID Bodega");

        txtIdBodega.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIdBodega.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Bodega", "Nombre Bodega", "Bodega Ubicacion"
            }
        ));
        tablaStock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaStockAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaStockMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaStock);

        label14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label14.setText("Bodega Ubicacion");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Bodega");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        cboxTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Bodega", "Bodega Nombre", "Ubicacion" }));
        cboxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoBusquedaActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 227, 250));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        label19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label19.setText("*Dar doble click a la fila deseada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(cboxTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label19)
                                .addGap(221, 221, 221))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscar))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(label15)
                                            .addGap(53, 53, 53)
                                            .addComponent(txtIdBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtUbicacionBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label21)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNombreBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdyda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(cboxTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label15)
                            .addComponent(txtIdBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar)
                            .addComponent(btnActualizar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReportes)
                            .addComponent(btnAdyda)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label21)
                            .addComponent(txtNombreBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUbicacionBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(label19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdydaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdydaActionPerformed
        Vista.Logistica.frmAyuda ventanaAyuda = new Vista.Logistica.frmAyuda();

        ventanaAyuda.setVisible(true);
        ventanaAyuda.setLocationRelativeTo(null);

        //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        try {
        String ruta = "C:\\Users\\ferit\\Desktop\\proyFinalP32K26b\\proyectop32k26b\\proyectop32k26b\\src\\main\\java\\Ayudas\\Logistica\\Logistica.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnAdydaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       txtIdBodega.setText("");
        txtNombreBodega.setText("");
        txtUbicacionBodega.setText("");
        txtBuscar.setText("");
        tablaStock.clearSelection();
        if (tablaStock.getRowSorter() != null) {
            tablaStock.setRowSorter(null);
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tablaStockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaStockAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaStockAncestorAdded

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

    if (tablaStock.getRowSorter() != null) {
        tablaStock.setRowSorter(null);
    }

    txtBuscar.setText("");
    cboxTipoBusqueda.setSelectedIndex(0);

    txtIdBodega.setText("");
    txtNombreBodega.setText("");
    txtUbicacionBodega.setText("");

    tablaStock.clearSelection();

    JOptionPane.showMessageDialog(this, "Formulario de Bodega restablecido correctamente.");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        Vista.Logistica.frmReportes ventana = new Vista.Logistica.frmReportes();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void cboxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoBusquedaActionPerformed
        // TODO add your handling code here:

        // Oculta todos los campos de búsqueda al inicio
        // para evitar que aparezcan controles innecesarios
        /*    txtBuscar.setVisible(false);
        fechaInicio.setVisible(false);
        fechaFin.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        btnBuscar.setVisible(false);
        */
        String seleccion = cboxTipoBusqueda.getSelectedItem().toString();

        switch (seleccion) {
            case "ID Bodega":
            buscarPorIDbodega();
            break;
            case "Nombre Bodega":
            buscarPorNombreBodega();
            break;
           case "Bodega Ubicacion":
            buscarPorUbicacion();
            break;
           
        }
    }//GEN-LAST:event_cboxTipoBusquedaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    int filaVisual = tablaStock.getSelectedRow();

    if (filaVisual != -1) {
        int respuesta = JOptionPane.showConfirmDialog(this, 
                "¿Seguro que desea eliminar esta bodega?", 
                "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                int filaModelo = tablaStock.convertRowIndexToModel(filaVisual);

                Object valorId = modeloBodega.getValueAt(filaModelo, 0);
                int idBodega = Integer.parseInt(valorId.toString());

                Modelo.Logistica.BodegasDAO dao = new Modelo.Logistica.BodegasDAO();

                if (dao.eliminar(idBodega)) {
                    modeloBodega.removeRow(filaModelo);
                    
                    JOptionPane.showMessageDialog(this, "Bodega eliminada exitosamente.");
                    btnLimpiarActionPerformed(null);
                } else {
                    JOptionPane.showMessageDialog(this, "Error: No se pudo eliminar en la base de datos.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

      String filtro = txtBuscar.getText().trim();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modeloBodega);
        tablaStock.setRowSorter(sorter);

        if (filtro.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            int columnaIndex = cboxTipoBusqueda.getSelectedIndex();
            if(columnaIndex > 2) columnaIndex = 0; 
            
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro, columnaIndex));
        }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

   String nombre = txtNombreBodega.getText().trim();
    String ubicacion = txtUbicacionBodega.getText().trim();
    String idStr = txtIdBodega.getText().trim();
    
    if (nombre.isEmpty() || ubicacion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe llenar el Nombre y la Ubicación.");
        return;
    }

    try {
        Controlador.Logistica.clsBodegas bodega = new Controlador.Logistica.clsBodegas();
        bodega.setBodnombre(nombre);
        bodega.setBodubicacion(ubicacion);

        if (!idStr.isEmpty()) {
            bodega.setBodegaid(Integer.parseInt(idStr));
        }
        
        Modelo.Logistica.BodegasDAO dao = new Modelo.Logistica.BodegasDAO();

        if (dao.insertar(bodega)) {
            // Refrescamos la tabla trayendo los datos reales y actualizados desde MySQL
            cargarDatosTabla(); 

            JOptionPane.showMessageDialog(this, "Registro guardado exitosamente.");
            btnLimpiarActionPerformed(null); 
        } else {
            JOptionPane.showMessageDialog(this, "Error: El DAO no pudo insertar el registro.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: El ID debe ser un número válido.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String filtro = txtBuscar.getText().trim();

    if (filtro.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un valor para buscar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modeloBodega);
    tablaStock.setRowSorter(sorter);

    String seleccion = cboxTipoBusqueda.getSelectedItem().toString();
    int columnaIndex = 0;

    switch (seleccion) {
        case "ID Bodega": 
            columnaIndex = 0; 
            break;
        case "Bodega Nombre": 
            columnaIndex = 1; 
            break;
        case "Ubicacion": 
            columnaIndex = 2; 
            break;
        default: 
            columnaIndex = 0; 
            break;
    }

    try {
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro, columnaIndex));

        if (tablaStock.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No se encontraron coincidencias.");
        }
    } catch (Exception e) {
        System.err.println("Error en filtro: " + e.getMessage());
    
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cargarDatosTabla() {
    // Limpiamos el modelo por si acaso tuviera filas previas
    modeloBodega.setRowCount(0);
    
    try {
        Modelo.Logistica.BodegasDAO dao = new Modelo.Logistica.BodegasDAO();
        // Nota: Asumo que tu DAO tiene un método 'listar' o 'seleccionar' que devuelve un List.
        // Si se llama diferente (ej. obtenerBodegas()), cambia .listar() por el nombre real.
        java.util.List<Controlador.Logistica.clsBodegas> listaBodegas = dao.listar(); 
        
        if (listaBodegas != null) {
            for (Controlador.Logistica.clsBodegas bodega : listaBodegas) {
                Object[] fila = {
                    bodega.getBodegaid(),
                    bodega.getBodnombre(),
                    bodega.getBodubicacion()
                };
                modeloBodega.addRow(fila);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar los datos de las bodegas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    
    
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

      int filaVisual = tablaStock.getSelectedRow();

    if (filaVisual != -1) {
        try {
            String idStr = txtIdBodega.getText().trim();
            String nombre = txtNombreBodega.getText().trim();
            String ubicacion = txtUbicacionBodega.getText().trim();

            if (idStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El ID no puede estar vacío para modificar.");
                return;
            }
            Controlador.Logistica.clsBodegas bodega = new Controlador.Logistica.clsBodegas();
            bodega.setBodegaid(Integer.parseInt(idStr));
            bodega.setBodnombre(nombre);
            bodega.setBodubicacion(ubicacion);

            Modelo.Logistica.BodegasDAO dao = new Modelo.Logistica.BodegasDAO();
            if (dao.actualizar(bodega)) {
                int filaModelo = tablaStock.convertRowIndexToModel(filaVisual);
                
                modeloBodega.setValueAt(idStr, filaModelo, 0);
                modeloBodega.setValueAt(nombre, filaModelo, 1);
                modeloBodega.setValueAt(ubicacion, filaModelo, 2);

                JOptionPane.showMessageDialog(this, "Bodega actualizada correctamente.");
                btnLimpiarActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se encontró el registro en la BD.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: El ID debe ser numérico.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una fila de la tabla para modificar.");
    }
    
    
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tablaStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaStockMouseClicked
       if (evt.getClickCount() == 2) {
        int filaVisual = tablaStock.getSelectedRow();
        
        if (filaVisual != -1) {
            // Traduce el índice por si se usó el buscador/filtro
            int filaModelo = tablaStock.convertRowIndexToModel(filaVisual);
            
            // Pasamos los datos de la fila a los JTextFields correspondientes de Bodega
            txtIdBodega.setText(modeloBodega.getValueAt(filaModelo, 0).toString());
            txtNombreBodega.setText(modeloBodega.getValueAt(filaModelo, 1).toString());
            txtUbicacionBodega.setText(modeloBodega.getValueAt(filaModelo, 2).toString());
            
            // Aseguramos que permanezca bloqueado el ID
            txtIdBodega.setEditable(false);
        }
    }
    }//GEN-LAST:event_tablaStockMouseClicked

    private void buscarPorIDbodega() {

    }
    private void buscarPorNombreBodega() {

    }
    private void buscarPorUbicacion() {

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMantenimientoBodega().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAdyda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> cboxTipoBusqueda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label19;
    private javax.swing.JLabel label21;
    private javax.swing.JTable tablaStock;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdBodega;
    private javax.swing.JTextField txtNombreBodega;
    private javax.swing.JTextField txtUbicacionBodega;
    // End of variables declaration//GEN-END:variables
}
