/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 22-04-2026  1. Creacion MdiLogistica, implementaciones basicas
//Marco. Hernandez 9959-24-6201 24-04-2026  2. Implementacion de los formularios transportes, pedidos, stock, kardex 
//Boris de Leon    9959-24-6203 03-05-2026  3.Implementacion de seguridad en el MdiLogistica

package Vista.Logistica;


import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Controlador.clsUsuarioConectado;
import Modelo.PermisosDAO;
import java.util.List;
import Vista.Logistica.frmAyuda;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

//formulario


/**
 *
 * @author macoh
 */
public class MdiLogistica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MdiLogistica.class.getName());

    /**
     * Creates new form MdiLogistica
     */
    public MdiLogistica() {
        initComponents();
        // Obtiene el usuario logueado y sus permisos
        int usuId = clsUsuarioConectado.getUsuId();
        PermisosDAO permisosDAO = new PermisosDAO();
        List<Integer> appsPermitidas = permisosDAO.obtenerAplicacionesPermitidas(usuId);
        
        // Configura qué botones se ven
        configurarVisibilidadBotones(appsPermitidas);
    }
    // Método para bloquear o desbloquear opciones según los permisos
    public void configurarVisibilidadBotones(List<Integer> appsPermitidas) {
        
        // 1. Por seguridad, deshabilitar todas las opciones por defecto
        frmTansportes.setEnabled(false);
        frmKardex.setEnabled(false);
        frmStock.setEnabled(false);
        frmGestion.setEnabled(false);

        // 2. Recorrer la lista y encender solo las que el usuario tiene asignadas
        for (int codigoApp : appsPermitidas) {
            switch (codigoApp) {
                case 2000: //Cambiar por el código real de "Transportes" en la BD
                    frmTansportes.setEnabled(true);
                    break;
                case 2001: //Cambiar por el código real de "Kardex" en la BD
                    frmKardex.setEnabled(true);
                    break;
                case 2002: //Cambiar por el código real de "Stock" en la BD
                    frmStock.setEnabled(true);
                    break;
                case 2003: //Cambiar por el código real de "Gestión de Pedidos" en la BD
                    frmGestion.setEnabled(true);
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        mnuGeneral = new javax.swing.JMenuBar();
        mnuTransporte = new javax.swing.JMenu();
        frmTansportes = new javax.swing.JMenuItem();
        mnuInventario = new javax.swing.JMenu();
        frmKardex = new javax.swing.JMenuItem();
        frmMantenimientoProductos = new javax.swing.JMenuItem();
        frmMarcas = new javax.swing.JMenuItem();
        frmLinea = new javax.swing.JMenuItem();
        mnuEntradaSalida = new javax.swing.JMenu();
        frmKBodega = new javax.swing.JMenuItem();
        frmStock = new javax.swing.JMenuItem();
        mnuPedidos = new javax.swing.JMenu();
        frmGestion = new javax.swing.JMenuItem();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalirSistema = new javax.swing.JCheckBoxMenuItem();
        frmAyudain = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        mnuTransporte.setText("Transportes");
        mnuTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTransporteActionPerformed(evt);
            }
        });

        frmTansportes.setText("Lista Transportistas");
        frmTansportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmTansportesActionPerformed(evt);
            }
        });
        mnuTransporte.add(frmTansportes);

        mnuGeneral.add(mnuTransporte);

        mnuInventario.setText("Inventarios");

        frmKardex.setText("Kardex");
        frmKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmKardexActionPerformed(evt);
            }
        });
        mnuInventario.add(frmKardex);

        frmMantenimientoProductos.setText("Mantenimiento Productos");
        frmMantenimientoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMantenimientoProductosActionPerformed(evt);
            }
        });
        mnuInventario.add(frmMantenimientoProductos);

        frmMarcas.setText("Marcas");
        frmMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMarcasActionPerformed(evt);
            }
        });
        mnuInventario.add(frmMarcas);

        frmLinea.setText("Linea");
        frmLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmLineaActionPerformed(evt);
            }
        });
        mnuInventario.add(frmLinea);

        mnuGeneral.add(mnuInventario);

        mnuEntradaSalida.setText("Bodega");
        mnuEntradaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntradaSalidaActionPerformed(evt);
            }
        });

        frmKBodega.setText("Gestion Bodega");
        frmKBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmKBodegaActionPerformed(evt);
            }
        });
        mnuEntradaSalida.add(frmKBodega);

        frmStock.setText("Existencias");
        frmStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmStockActionPerformed(evt);
            }
        });
        mnuEntradaSalida.add(frmStock);

        mnuGeneral.add(mnuEntradaSalida);

        mnuPedidos.setText("Pedidos");

        frmGestion.setText("Gestion Pedidos");
        frmGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmGestionActionPerformed(evt);
            }
        });
        mnuPedidos.add(frmGestion);

        mnuGeneral.add(mnuPedidos);

        mnuArchivo.setText("Otros");
        mnuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoActionPerformed(evt);
            }
        });

        mnuSalirSistema.setSelected(true);
        mnuSalirSistema.setText("Salir del Sistema");
        mnuSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirSistemaActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalirSistema);

        frmAyudain.setSelected(true);
        frmAyudain.setText("Ayudas");
        frmAyudain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmAyudainActionPerformed(evt);
            }
        });
        mnuArchivo.add(frmAyudain);

        mnuGeneral.add(mnuArchivo);

        setJMenuBar(mnuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirSistemaActionPerformed
        // TODO add your handling code here:
        /*===== OPERACIÓN CERRAR SESIÓN ====
        Variable entera respuesta_cs*/

        int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea Cerrar Sesión?", "Cerrar Sesión",            JOptionPane.YES_NO_OPTION);

        if (respuesta_cs == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_mnuSalirSistemaActionPerformed

    private void mnuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuArchivoActionPerformed

    private void frmTansportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmTansportesActionPerformed
      
       System.out.println("Abriendo Informacion de Transportes");
    frmMantenimientoTransporte ventana = new frmMantenimientoTransporte();
    
   
    ventana.setVisible(true); 
    
    jDesktopPane1.add(ventana);
    
  
    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension FrameSize = ventana.getSize();
    ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    
    try {
        ventana.setSelected(true); 
    } catch (java.beans.PropertyVetoException e) {
        System.out.println("Error al seleccionar ventana: " + e);
    }
    ventana.toFront(); 
    }//GEN-LAST:event_frmTansportesActionPerformed

    private void mnuTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTransporteActionPerformed
       
    }//GEN-LAST:event_mnuTransporteActionPerformed

    private void frmKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmKardexActionPerformed
         System.out.println("Abriendo Informacion de Transportes");
    frmMantenimientoKardex ventana = new frmMantenimientoKardex();
    
    
    ventana.setVisible(true); 
    
    jDesktopPane1.add(ventana);
    
    
    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension FrameSize = ventana.getSize();
    ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    
   try {
        ventana.setSelected(true); 
    } catch (java.beans.PropertyVetoException e) {
        System.out.println("Error al seleccionar ventana: " + e);
    }
    
    ventana.toFront();
                                                 
    }//GEN-LAST:event_frmKardexActionPerformed

    private void frmGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmGestionActionPerformed
          System.out.println("Abriendo Informacion de Transportes");
    frmMantenimientoPedidos ventana = new frmMantenimientoPedidos();
    
    ventana.setSize(900, 600);
    ventana.setVisible(true); 
    
    jDesktopPane1.add(ventana);
    
  
    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension FrameSize = ventana.getSize();
    ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    
    ventana.setVisible(true); 
    try {
        ventana.setSelected(true); 
    } catch (java.beans.PropertyVetoException e) {
        System.out.println("Error al seleccionar ventana: " + e);
    }
    ventana.toFront(); 
    }//GEN-LAST:event_frmGestionActionPerformed

    private void frmStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmStockActionPerformed
         System.out.println("Abriendo Informacion de Transportes");
    frmMantenimientoStock ventana = new frmMantenimientoStock();
    
   
    ventana.setVisible(true); 
    
    jDesktopPane1.add(ventana);
    
  
    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension FrameSize = ventana.getSize();
    ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    
    try {
        ventana.setSelected(true); 
    } catch (java.beans.PropertyVetoException e) {
        System.out.println("Error al seleccionar ventana: " + e);
    }
    ventana.toFront(); 
                               
    }//GEN-LAST:event_frmStockActionPerformed

    private void frmAyudainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmAyudainActionPerformed
Vista.Logistica.frmAyuda ventana = new Vista.Logistica.frmAyuda();
    ventana.setVisible(true);
    ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_frmAyudainActionPerformed

    private void frmKBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmKBodegaActionPerformed
      boolean abierta = false;
    for (javax.swing.JInternalFrame f : jDesktopPane1.getAllFrames()) {
        if (f instanceof frmMantenimientoBodega) {
            abierta = true;
            f.toFront(); // Si ya existe, solo la traemos al frente
            try { f.setSelected(true); } catch (Exception e) {}
            break;
        }
    }

    if (!abierta) {
        frmMantenimientoBodega ventana = new frmMantenimientoBodega();
        jDesktopPane1.add(ventana);
        
        // Centrar
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, 
                            (desktopSize.height - FrameSize.height) / 2);
        
        ventana.setVisible(true);
    }
    }//GEN-LAST:event_frmKBodegaActionPerformed

    private void mnuEntradaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntradaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuEntradaSalidaActionPerformed

    private void frmMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMarcasActionPerformed
        // TODO add your handling code here:
        System.out.println("Abriendo Informacion de Marcas");
    frmMarcas ventana = new frmMarcas();
    
    ventana.setSize(900, 600);
    ventana.setVisible(true); 
    
    jDesktopPane1.add(ventana);
    
  
    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension FrameSize = ventana.getSize();
    ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    
    ventana.setVisible(true); 
    try {
        ventana.setSelected(true); 
    } catch (java.beans.PropertyVetoException e) {
        System.out.println("Error al seleccionar ventana: " + e);
    }
    ventana.toFront(); 
    }//GEN-LAST:event_frmMarcasActionPerformed

    private void frmMantenimientoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMantenimientoProductosActionPerformed
        // TODO add your handling code here:
    System.out.println("Abriendo Informacion de Productos");
    frmMantenimientoProductos ventana = new frmMantenimientoProductos();
    
    ventana.setSize(900, 600);
    ventana.setVisible(true); 
    
    jDesktopPane1.add(ventana);
    
  
    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension FrameSize = ventana.getSize();
    ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    
    ventana.setVisible(true); 
    try {
        ventana.setSelected(true); 
    } catch (java.beans.PropertyVetoException e) {
        System.out.println("Error al seleccionar ventana: " + e);
    }
    ventana.toFront(); 
    }//GEN-LAST:event_frmMantenimientoProductosActionPerformed

    private void frmLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmLineaActionPerformed
        // TODO add your handling code here:
         System.out.println("Abriendo Informacion de Linea");
    frmLinea ventana = new frmLinea();
    
    ventana.setSize(900, 600);
    ventana.setVisible(true); 
    
    jDesktopPane1.add(ventana);
    
  
    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension FrameSize = ventana.getSize();
    ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    
    ventana.setVisible(true); 
    try {
        ventana.setSelected(true); 
    } catch (java.beans.PropertyVetoException e) {
        System.out.println("Error al seleccionar ventana: " + e);
    }
    ventana.toFront(); 
    }//GEN-LAST:event_frmLineaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MdiLogistica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem frmAyudain;
    private javax.swing.JMenuItem frmGestion;
    private javax.swing.JMenuItem frmKBodega;
    private javax.swing.JMenuItem frmKardex;
    private javax.swing.JMenuItem frmLinea;
    private javax.swing.JMenuItem frmMantenimientoProductos;
    private javax.swing.JMenuItem frmMarcas;
    private javax.swing.JMenuItem frmStock;
    private javax.swing.JMenuItem frmTansportes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuEntradaSalida;
    private javax.swing.JMenuBar mnuGeneral;
    private javax.swing.JMenu mnuInventario;
    private javax.swing.JMenu mnuPedidos;
    private javax.swing.JCheckBoxMenuItem mnuSalirSistema;
    private javax.swing.JMenu mnuTransporte;
    // End of variables declaration//GEN-END:variables
}
