/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.vistaCuentasCorrientes;

import Controlador.controladorCuentasCorrientes.clscuentasporpagar;
import Modelo.modeloCuentasCorrientes.cuentasporpagarDAO;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author miais
 */
public class cuentasporpagar extends javax.swing.JFrame {

    /**
     * Creates new form cuentasporpagar
     */
    public cuentasporpagar() {
        initComponents();
    }
    
    
    //Método para llenar tabla 
    private void llenarTabla(List<clscuentasporpagar> lista) {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Código");
    modelo.addColumn("Proveedor código");
    modelo.addColumn("Acreedor código");
    modelo.addColumn("Venid");
    modelo.addColumn("Fecha emisión");
    modelo.addColumn("Monto total");
    modelo.addColumn("Saldo pendiente");
    modelo.addColumn("Estado");
    modelo.addColumn("TTid");
    modelo.addColumn("Origen id");

    for (clscuentasporpagar cxp : lista) {
        Object[] fila = {
            cxp.getCppcodigo(),
            cxp.getProcodigo(),
            cxp.getAcrecodigo(),
            cxp.getVenid(),
            cxp.getCppfechaemision(),
            cxp.getCppcmontototal(),
            cxp.getCppsaldopendiente(),
            cxp.getCppestado(),
            cxp.getTTid(),
            cxp.getCpporigenid()
        };
        modelo.addRow(fila);
    }
    jTable1.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Cuentas Por Pagar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Proveedor", "Acreedor", "Estado", "Fechas", "Monto Total", "Saldo pendiente" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setText("Campo de búsqueda");

        jLabel2.setText("Fecha Final");

        jLabel3.setText("Fecha Inicio");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ayuda");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Proveedor código", "Acreedor código", "Venid", "Fecha emision", "Monto total", "Saldo pendiente", "Estado", "TTid", "Origen id"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Editar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(408, 408, 408)
                .addComponent(jButton3)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton1)
                        .addGap(52, 52, 52)
                        .addComponent(jButton2)
                        .addGap(56, 56, 56)
                        .addComponent(jButton4)
                        .addGap(46, 46, 46)
                        .addComponent(jButton5)
                        .addGap(57, 57, 57)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cuentasporpagarDAO dao = new cuentasporpagarDAO();
        String tipoBusqueda = jComboBox1.getSelectedItem().toString();

        try {
            switch (tipoBusqueda) {
                case "Código":
                    clscuentasporpagar cxp = new clscuentasporpagar();
                    cxp.setCppcodigo(Integer.parseInt(jTextField1.getText().trim()));
                    clscuentasporpagar resultado = dao.queryPorCodigo(cxp);
                    List<clscuentasporpagar> listaCodigo = new java.util.ArrayList<>();
                    if (resultado.getCppcodigo() != 0) listaCodigo.add(resultado);
                    llenarTabla(listaCodigo);
                    break;

                case "Proveedor":
                    llenarTabla(dao.queryPorProveedor(Integer.parseInt(jTextField1.getText().trim())));
                    break;

                case "Acreedor":
                    llenarTabla(dao.queryPorAcreedor(Integer.parseInt(jTextField1.getText().trim())));
                    break;

                case "Estado":
                    llenarTabla(dao.queryPorEstado(jTextField1.getText().trim().charAt(0)));
                    break;

                case "Monto total":
                    llenarTabla(dao.queryPorMonto(Float.parseFloat(jTextField1.getText().trim())));
                    break;

                case "Saldo pendiente":
                    llenarTabla(dao.queryPorSaldo(Float.parseFloat(jTextField1.getText().trim())));
                    break;

                case "Fechas":
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String fechaInicio = sdf.format(jDateChooser1.getDate());
                    String fechaFin = sdf.format(jDateChooser2.getDate());
                    llenarTabla(dao.queryPorFechas(fechaInicio, fechaFin));
                    break;

                default:
                    llenarTabla(dao.select());
                    break;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al buscar: " + e.getMessage(),
                "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        jComboBox1.setSelectedIndex(0);
        jTable1.setModel(new DefaultTableModel());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            clscuentasporpagar cxp = new clscuentasporpagar();
            cxp.setProcodigo(Integer.parseInt(JOptionPane.showInputDialog("Código de proveedor:")));
            cxp.setAcrecodigo(Integer.parseInt(JOptionPane.showInputDialog("Código de acreedor:")));
            cxp.setVenid(Integer.parseInt(JOptionPane.showInputDialog("Venid:")));
            cxp.setCppcmontototal(Float.parseFloat(JOptionPane.showInputDialog("Monto total:")));
            cxp.setCppsaldopendiente(Float.parseFloat(JOptionPane.showInputDialog("Saldo pendiente:")));
            cxp.setCppestado(JOptionPane.showInputDialog("Estado (A/I):").charAt(0));
            cxp.setTTid(Integer.parseInt(JOptionPane.showInputDialog("TTid:")));
            cxp.setCpporigenid(Integer.parseInt(JOptionPane.showInputDialog("Origen id:")));

            cuentasporpagarDAO dao = new cuentasporpagarDAO();
            int resultado = dao.insert(cxp);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Registro agregado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo agregar.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            clscuentasporpagar cxp = new clscuentasporpagar();
            cxp.setCppcodigo((int) jTable1.getValueAt(fila, 0));
            cxp.setProcodigo(Integer.parseInt(JOptionPane.showInputDialog("Nuevo código de proveedor:", jTable1.getValueAt(fila, 1))));
            cxp.setAcrecodigo(Integer.parseInt(JOptionPane.showInputDialog("Nuevo código de acreedor:", jTable1.getValueAt(fila, 2))));
            cxp.setVenid(Integer.parseInt(JOptionPane.showInputDialog("Nuevo Venid:", jTable1.getValueAt(fila, 3))));
            cxp.setCppfechaemision(JOptionPane.showInputDialog("Nueva fecha (yyyy-MM-dd):", jTable1.getValueAt(fila, 4)));
            cxp.setCppcmontototal(Float.parseFloat(JOptionPane.showInputDialog("Nuevo monto total:", jTable1.getValueAt(fila, 5))));
            cxp.setCppsaldopendiente(Float.parseFloat(JOptionPane.showInputDialog("Nuevo saldo pendiente:", jTable1.getValueAt(fila, 6))));
            cxp.setCppestado(JOptionPane.showInputDialog("Nuevo estado (A/I):", jTable1.getValueAt(fila, 7)).charAt(0));
            cxp.setTTid(Integer.parseInt(JOptionPane.showInputDialog("Nuevo TTid:", jTable1.getValueAt(fila, 8))));
            cxp.setCpporigenid(Integer.parseInt(JOptionPane.showInputDialog("Nuevo origen id:", jTable1.getValueAt(fila, 9))));

            cuentasporpagarDAO dao = new cuentasporpagarDAO();
            int resultado = dao.update(cxp);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Registro actualizado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirmar = JOptionPane.showConfirmDialog(this,
            "¿Está seguro que desea eliminar este registro?",
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {
            try {
                clscuentasporpagar cxp = new clscuentasporpagar();
                cxp.setCppcodigo((int) jTable1.getValueAt(fila, 0));

                cuentasporpagarDAO dao = new cuentasporpagarDAO();
                int resultado = dao.delete(cxp);
                if (resultado > 0) {
                    JOptionPane.showMessageDialog(this, "Registro eliminado correctamente.");
                    ((DefaultTableModel) jTable1.getModel()).removeRow(fila);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuentasporpagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuentasporpagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuentasporpagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuentasporpagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuentasporpagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
