/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.vistaCuentasCorrientes;

import Controlador.clsUsuarioConectado;
import Controlador.controladorCuentasCorrientes.clsAcreedor;
import Controlador.controladorCuentasCorrientes.clsFacturaCompraAcreedor;
import Modelo.BitacoraDAO;
import java.math.RoundingMode;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import static java.util.FormatProcessor.FMT;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author astri
 */

/**
 * Formulario CRUD completo: Factura de Compra – Acreedores
 *
 * Lógica IVA:
 *   Total ingresado YA incluye IVA.
 *   Subtotal = Total / 1.12
 *   IVA      = Total - Subtotal
 *
 * Bitácora:
 *   4025 = Insertar  |  4026 = Buscar
 *   4027 = Anular    |  4028 = Modificar  |  4029 = Eliminar
 */
public class FrmFacturaCompraAcreedor extends javax.swing.JInternalFrame {
// =
 
    // =========================================================
    // DATOS EN MEMORIA
    // =========================================================
    private List<clsAcreedor> listaAcreedores = new ArrayList<>();
    private int facComIdActual = 0;
    int idUsuario = clsUsuarioConectado.getUsuId();
    /**
     * Creates new form FrmFacturaCompraAcreedor
     */
    public FrmFacturaCompraAcreedor() {
        initComponents();
        llenadoDeCombos();
        llenadoDeTablas();
        cargarPermisos();
        mostrarFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtIdFactura = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        cmbAcreedor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFacturas = new javax.swing.JTable();
        btsActualizar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        btsBuscar = new javax.swing.JButton();
        btsRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btsAnular = new javax.swing.JButton();
        btsEliminar = new javax.swing.JButton();
        btsLimpiar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datos de la factura:");

        jLabel2.setText("Acreedor:");

        jLabel3.setText("No. Factura:");

        jLabel4.setText("Fecha:");

        jLabel5.setText("ID Factura:");

        jLabel6.setText("Total (Q):");

        jLabel7.setText("Subtotal (Q):");

        jLabel8.setText("IVA 12%:");

        jLabel9.setText("Estado");

        txtIdFactura.setEditable(false);
        txtIdFactura.setBackground(new java.awt.Color(240, 240, 240));

        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
        });

        txtSubtotal.setEditable(false);
        txtSubtotal.setBackground(new java.awt.Color(240, 240, 240));

        txtIva.setEditable(false);
        txtIva.setBackground(new java.awt.Color(240, 240, 240));

        txtEstado.setEditable(false);
        txtEstado.setBackground(new java.awt.Color(240, 240, 240));

        cmbAcreedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Montos:");

        tablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "No. Factura", "Acreedor", "Fecha", "SubTotal", "IVA", "TOTAL", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaFacturas);

        btsActualizar.setText("Actualizar");
        btsActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsActualizarActionPerformed(evt);
            }
        });

        jLabel11.setText("ID a buscar:");

        btsBuscar.setText("Buscar");
        btsBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsBuscarActionPerformed(evt);
            }
        });

        btsRegistrar.setText("Registrar");
        btsRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modficar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btsAnular.setText("Anular");
        btsAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsAnularActionPerformed(evt);
            }
        });

        btsEliminar.setText("Eliminar");
        btsEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsEliminarActionPerformed(evt);
            }
        });

        btsLimpiar.setText("Limpiar");
        btsLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsLimpiarActionPerformed(evt);
            }
        });

        btnReportes.setText("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(cmbAcreedor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNumFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtIdFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(89, 89, 89)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btsRegistrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btsAnular)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btsBuscar)
                                .addGap(212, 212, 212)
                                .addComponent(btsActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btsEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btsLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReportes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbAcreedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btsActualizar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btsBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btsRegistrar)
                            .addComponent(btnModificar)
                            .addComponent(btsAnular))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsEliminar)
                    .addComponent(btsLimpiar)
                    .addComponent(btnReportes))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void llenadoDeCombos() {
        cmbAcreedor.removeAllItems();
        listaAcreedores.clear();
        cmbAcreedor.addItem("Seleccione un acreedor");
        try {
            clsAcreedor filtro = new clsAcreedor();
            filtro.setAcreEstado("A");
            listaAcreedores = new clsAcreedor().getBuscarAcreedoresPorEstado(filtro);
            for (clsAcreedor a : listaAcreedores) {
                cmbAcreedor.addItem(a.getAcreCodigo() + " - " + a.getAcreNombre());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                "Error al cargar acreedores:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
 
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("N° Factura");
        modelo.addColumn("Acreedor");
        modelo.addColumn("Fecha");
        modelo.addColumn("Subtotal");
        modelo.addColumn("IVA");
        modelo.addColumn("Total");
        modelo.addColumn("Estado");
 
        clsFacturaCompraAcreedor fac = new clsFacturaCompraAcreedor();
        List<clsFacturaCompraAcreedor> lista = fac.getListadoFacturasCompra();
        tablaFacturas.setModel(modelo);
 
        for (clsFacturaCompraAcreedor f : lista) {
            modelo.addRow(new Object[]{
                f.getFacComId(),
                f.getFacComNumero(),
                buscarNombreAcreedor(f.getAcreCodigo()),
                f.getFacComFecha(),
                "Q " + f.getFacComSubtotal(),
                "Q " + f.getFacComIva(),
                "Q " + f.getFacComTotal(),
                f.getFacComEstado()
            });
        }
    }
 
    private String buscarNombreAcreedor(int acreCodigo) {
        for (clsAcreedor a : listaAcreedores) {
            if (a.getAcreCodigo() == acreCodigo) return a.getAcreNombre();
        }
        return String.valueOf(acreCodigo);
    }
 
    public void cargarPermisos() {
        // Descomenta cuando tengas los códigos de permisos
        // int usuId = clsUsuarioConectado.getUsuId();
        // PermisosDAO permisosDAO = new PermisosDAO();
        // btnRegistrar.setEnabled( permisosDAO.puedeInsertar (usuId, 4025) );
        // btnBuscar.setEnabled   ( permisosDAO.puedeBuscar   (usuId, 4026) );
        // btnAnular.setEnabled   ( permisosDAO.puedeEliminar (usuId, 4027) );
        // btnModificar.setEnabled( permisosDAO.puedeModificar(usuId, 4028) );
        // btnEliminar.setEnabled ( permisosDAO.puedeEliminar (usuId, 4029) );
        // btnReportes.setEnabled ( permisosDAO.puedeReportar (usuId, 4030) );
    }
 
    private void mostrarFecha() {
    DateTimeFormatter formato =
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    txtFecha.setText(LocalDateTime.now().format(formato));
}


// LÓGICA IVA 
private void calcularDesdeTotal() {
    try {

        String s = txtTotal.getText().trim();

        if (s.isEmpty()) {
            txtSubtotal.setText("0.00");
            txtIva.setText("0.00");
            return;
        }

        double total = Double.parseDouble(s);

        double subtotal = total / 1.12;
        double iva = total - subtotal;

        txtSubtotal.setText(String.format("%.2f", subtotal));
        txtIva.setText(String.format("%.2f", iva));

    } catch (NumberFormatException ex) {

        txtSubtotal.setText("0.00");
        txtIva.setText("0.00");

    }
}
private void cargarFacturaEnForm(clsFacturaCompraAcreedor f) {
        facComIdActual = f.getFacComId();
        txtIdFactura.setText(String.valueOf(f.getFacComId()));
        txtNumFactura.setText(f.getFacComNumero());
        txtFecha.setText(f.getFacComFecha());
        txtTotal.setText(String.valueOf(f.getFacComTotal()));
        txtSubtotal.setText(String.valueOf(f.getFacComSubtotal()));
        txtIva.setText(String.valueOf(f.getFacComIva()));
        txtEstado.setText(f.getFacComEstado());
        for (int i = 0; i < listaAcreedores.size(); i++) {
            if (listaAcreedores.get(i).getAcreCodigo() == f.getAcreCodigo()) {
                cmbAcreedor.setSelectedIndex(i + 1); break;
            }
        }
    }
 
    public void limpiarTextos() {
        facComIdActual = 0;
        txtIdFactura.setText("");
        txtbuscado.setText("");
        txtNumFactura.setText("");
        txtTotal.setText("");
        txtSubtotal.setText("0.00");
        txtIva.setText("0.00");
        txtEstado.setText("");
        cmbAcreedor.setSelectedIndex(0);
        mostrarFecha();
    }

 
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    if (facComIdActual <= 0) {
            JOptionPane.showMessageDialog(null,
                "Primero busque la factura que desea modificar.",
                "Validación", JOptionPane.WARNING_MESSAGE); return;
        }
        if (txtNumFactura.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                "El número de factura no puede estar vacío.",
                "Validación", JOptionPane.WARNING_MESSAGE); return;
        }
        double total;
        try {
            total = Double.parseDouble(txtTotal.getText().trim());
             if (total <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un total válido mayor a 0.",
                "Validación", JOptionPane.WARNING_MESSAGE); return;
        }
 
        double subtotal = total / 1.12;
        double iva = total - subtotal;
        int acreCod = listaAcreedores.get(cmbAcreedor.getSelectedIndex() - 1).getAcreCodigo();
 
        clsFacturaCompraAcreedor fac = new clsFacturaCompraAcreedor();
        fac.setFacComId(facComIdActual);
        fac.setFacComNumero(txtNumFactura.getText().trim());
        fac.setFacComFecha(txtFecha.getText());
        fac.setProCodigo(999);
        fac.setAcreCodigo(acreCod);
        fac.setFacComSubtotal(subtotal);
        fac.setFacComIva(iva);
        fac.setFacComTotal(total);
        fac.setFacComEstado(txtEstado.getText().trim());
 
        int rows = fac.setModificarFacturaCompra(fac);
        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "Registro Modificado\n",
                "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
            new BitacoraDAO().insert(idUsuario, 4028, "Modificar Factura Acreedor");
            llenadoDeTablas();
            limpiarTextos();
        } else {
            JOptionPane.showMessageDialog(null, "Error al modificar la factura.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btsRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsRegistrarActionPerformed
        // TODO add your handling code here:
    if (cmbAcreedor.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un acreedor.",
                "Validación", JOptionPane.WARNING_MESSAGE); return;
        }
        if (txtNumFactura.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el número de factura.",
                "Validación", JOptionPane.WARNING_MESSAGE); return;
        }
        double total;
        try {
            total = Double.parseDouble(txtTotal.getText().trim());

    if (total <= 0) {
        throw new NumberFormatException();
    }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un total válido mayor a 0.",
                "Validación", JOptionPane.WARNING_MESSAGE);
            txtTotal.requestFocus(); return;
        }
 
       double subtotal = total / 1.12;
       double iva = total - subtotal;

        int acreCod = listaAcreedores.get(cmbAcreedor.getSelectedIndex() - 1).getAcreCodigo();
 
        clsFacturaCompraAcreedor fac = new clsFacturaCompraAcreedor();
        fac.setFacComNumero(txtNumFactura.getText().trim());
        fac.setFacComFecha(txtFecha.getText());
        fac.setProCodigo(999);
        fac.setAcreCodigo(acreCod);
        fac.setFacComSubtotal(subtotal);
        fac.setFacComIva(iva);
        fac.setFacComTotal(total);
        fac.setFacComEstado("Vigente");
 
        int confirm = JOptionPane.showConfirmDialog(null,
            "¿Confirmar registro de factura?\n\n" +
      
                    "Acreedor  : " + cmbAcreedor.getSelectedItem() + "\n" +
            "N° Factura: " + fac.getFacComNumero()          + "\n" +
            "Subtotal  : Q " + subtotal                     + "\n" +
            "IVA       : Q " + iva                          + "\n" +
            "Total     : Q " + total,
            "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;
 
        int nuevoId = fac.setIngresarFacturaCompra(fac);
        if (nuevoId > 0) {
            facComIdActual = nuevoId;
            txtIdFactura.setText(String.valueOf(nuevoId));
            txtEstado.setText("Vigente");
            JOptionPane.showMessageDialog(null,
                "Registro Ingresado\n",
                "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
            new BitacoraDAO().insert(idUsuario, 4025, "Insertar Factura Acreedor");
            llenadoDeTablas();
            limpiarTextos();
        } else {
            JOptionPane.showMessageDialog(null,
                "Error al registrar. Verifique que el N° de factura no esté duplicado.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btsRegistrarActionPerformed

    private void btsBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsBuscarActionPerformed
        // TODO add your handling code here:
    if (txtbuscado.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el ID a buscar.",
                "Validación", JOptionPane.WARNING_MESSAGE); return;
        }
        try {
            clsFacturaCompraAcreedor filtro = new clsFacturaCompraAcreedor();
            filtro.setFacComId(Integer.parseInt(txtbuscado.getText().trim()));
            clsFacturaCompraAcreedor enc = filtro.getBuscarFacturaPorId(filtro);
 
            if (enc == null) {
                JOptionPane.showMessageDialog(null,
                    "No se encontró factura con ID: " + txtbuscado.getText(),
                    "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            cargarFacturaEnForm(enc);
            new BitacoraDAO().insert(idUsuario, 4026, "Buscar Factura Acreedor");
 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID debe ser un número.",
                "Validación", JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_btsBuscarActionPerformed

    private void btsAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsAnularActionPerformed
        // TODO add your handling code here:
        if (facComIdActual <= 0) {
            JOptionPane.showMessageDialog(null,
                "Primero busque la factura que desea anular.",
                "Validación", JOptionPane.WARNING_MESSAGE); return;
        }
        int confirm = JOptionPane.showConfirmDialog(null,
            "¿Anular la factura " + txtNumFactura.getText() + "?\n" +
            "El registro se conserva como 'Anulada'.",
            "Confirmar Anulación",
            JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) return;
 
        clsFacturaCompraAcreedor fac = new clsFacturaCompraAcreedor();
        fac.setFacComId(facComIdActual);
 
        int rows = fac.setAnularFacturaCompra(fac);
        if (rows > 0) {
            txtEstado.setText("Anulada");
            JOptionPane.showMessageDialog(null, "Factura anulada correctamente.\n",
                "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
            new BitacoraDAO().insert(idUsuario, 4027, "Anular Factura Acreedor");
            llenadoDeTablas();
            limpiarTextos();
        } else {
            JOptionPane.showMessageDialog(null, "Error al anular la factura.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btsAnularActionPerformed

    private void btsEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsEliminarActionPerformed
        // TODO add your handling code here:
    if (facComIdActual <= 0) {
            JOptionPane.showMessageDialog(null,
                "Primero busque la factura que desea eliminar.",
                "Validación", JOptionPane.WARNING_MESSAGE); return;
        }
        int confirm = JOptionPane.showConfirmDialog(null,
            "¿Eliminar DEFINITIVAMENTE la factura " + txtNumFactura.getText() + "?\n" +
            "Esta acción NO se puede deshacer.",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) return;
 
        clsFacturaCompraAcreedor fac = new clsFacturaCompraAcreedor();
        fac.setFacComId(facComIdActual);
 
        int rows = fac.setEliminarFacturaCompra(fac);
        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "Registro Borrado\n",
                "Información del Sistema", JOptionPane.INFORMATION_MESSAGE);
            new BitacoraDAO().insert(idUsuario, 4029, "Eliminar Factura Acreedor");
            llenadoDeTablas();
            limpiarTextos();
        } else {
            JOptionPane.showMessageDialog(null, "Error al eliminar la factura.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btsEliminarActionPerformed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
        // TODO add your handling code here:
        calcularDesdeTotal();
    }//GEN-LAST:event_txtTotalKeyReleased

    private void btsActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsActualizarActionPerformed
        // TODO add your handling code here:
        llenadoDeTablas();
    }//GEN-LAST:event_btsActualizarActionPerformed

    private void btsLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarTextos();
    }//GEN-LAST:event_btsLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFacturaCompraAcreedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFacturaCompraAcreedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFacturaCompraAcreedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFacturaCompraAcreedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFacturaCompraAcreedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btsActualizar;
    private javax.swing.JButton btsAnular;
    private javax.swing.JButton btsBuscar;
    private javax.swing.JButton btsEliminar;
    private javax.swing.JButton btsLimpiar;
    private javax.swing.JButton btsRegistrar;
    private javax.swing.JComboBox<String> cmbAcreedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFacturas;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdFactura;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
