/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.PrototipoEFP32026;

import Controlador.clsBitacora;
import Controlador.Prototipo.clsCarreras;
import Controlador.clsUsuarioConectado;
import Controlador.controladorPlanilla.clsBitacoraPlanilla;
import Modelo.BitacoraDAO;
import Modelo.Conexion;
import Modelo.Prototipo.CarrerasDAO;
import java.awt.Desktop;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import Modelo.modeloPlanilla.BitacoraPlanillaDAO;
import Controlador.controladorPlanilla.clsBitacoraPlanilla;

/**
 *
 * @author marlo
 */
public class frmCarreras extends javax.swing.JFrame {

    /**
     * Creates new form frmCarreras
     */
    public frmCarreras() {
        initComponents();
         
        llenadoDeTablas();
        
    }
    
     private clsBitacora crearBitacora(String accion) {

        clsBitacora bitacora = new clsBitacora();

        try {

            BitacoraDAO dao = new BitacoraDAO();

            int usuario = 1;

            try {
                usuario = clsUsuarioConectado.getUsuId();
            } catch (Exception e) {
                System.out.println("Usuario no definido");
            }

            bitacora.setUsucodigo(usuario);

            bitacora.setAplcodigo(2);

            bitacora.setBitfecha(dao.fechaActual());

            bitacora.setBitip(java.net.InetAddress.getLocalHost().getHostAddress());

            bitacora.setBitequipo(java.net.InetAddress.getLocalHost().getHostName());

            bitacora.setBitaccion(accion);

        } catch (Exception e) {
            e.printStackTrace();
        }

        return bitacora;
    }

    
    public void llenadoDeTablas() {

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre Carrera");
        modelo.addColumn("Codigo facultad");
        modelo.addColumn("Estatus");

        tblCarreras.setModel(modelo);

        CarrerasDAO dao = new CarrerasDAO();

        clsBitacora bitacora = crearBitacora("Consulta de Carreras");

        List<clsCarreras> lista = dao.obtenerCarreras(bitacora);

        String[] dato = new String[6];

        for (clsCarreras e : lista) {

            dato[0] = String.valueOf(e.getEmpcodigo());
            dato[1] = e.getEmpnombre();
            dato[2] = String.valueOf(e.getPuecodigo());
            dato[3] = String.valueOf(e.getPuecodigo());
            

            modelo.addRow(dato);
        }
    }
    
    
    public void limpiarTextos() {

        txtCodigo.setText("");
        txtNombre.setText("");
        txtDPI.setText("");
        txtEstatus.setText("");
        txtBuscar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarreras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDPI = new javax.swing.JTextField();
        txtEstatus = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnSalida = new javax.swing.JButton();
        btnayuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre carrera", "Codigo facultad", "Estatus"
            }
        ));
        jScrollPane1.setViewportView(tblCarreras);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mantenimiento Carreras");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nombre Carrera:");

        jLabel4.setText("Codigo Facultad:");

        jLabel5.setText("Estatus:");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPIActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Reportes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnSalida.setText("Salida");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        btnayuda.setText("AYUDA");
        btnayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnayuda)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(btnSalida))
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnRegistrar)
                                            .addComponent(jLabel5)
                                            .addComponent(jButton4))
                                        .addGap(32, 32, 32)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnModificar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminar))
                                    .addComponent(jButton5)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(30, 30, 30)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnSalida)
                    .addComponent(btnayuda))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if(txtNombre.getText().trim().isEmpty() ||
            txtDPI.getText().trim().isEmpty() ||
            txtEstatus.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null, "Complete los campos");
            return;
        }

        try {

            clsCarreras empleado = new clsCarreras();

            empleado.setEmpnombre(txtNombre.getText().trim());

            empleado.setEmpdpi(txtDPI.getText().trim());

            empleado.setPuecodigo(
                Integer.parseInt(txtEstatus.getText())
            );

   

            // Estado desde ComboBox
            if(cboEstatus.getSelectedItem().toString().equals("Activo")){

                empleado.setEmpestado(1);

            }else{

                empleado.setEmpestado(0);
            }

            CarrerasDAO dao = new CarrerasDAO();

            clsBitacora bitacora = crearBitacora("Insertar empleado");

            int resultado = dao.insertarEmpleado(empleado, bitacora);

            if(resultado > 0){
                
            BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6003);

            bitacoraPlanilla.setAccion("Registrar");

            bitacoraPlanilla.setTablaAfectada("empleados");

            bitacoraPlanilla.setDescripcion(
            "Se registró un empleado"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );

            


                llenadoDeTablas();

                limpiarTextos();

            }else{

                JOptionPane.showMessageDialog(null,
                    "No se pudo registrar.\n" +
                    "Verifique:\n" +
                    "- DPI duplicado\n" +
                    "- Puesto existente\n" +
                    "- Bitácora\n" +
                    "- Fecha");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Código de puesto inválido");

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(null,
                "Fecha inválida. Use formato YYYY-MM-DD");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
                "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(txtBuscar.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null, "Ingrese un ID");
            return;
        }

        try {

            int id = Integer.parseInt(txtBuscar.getText());

            CarrerasDAO dao = new CarrerasDAO();

            clsBitacora bitacora = crearBitacora("Buscar empleado");

            clsCarreras empleado = dao.obtenerEmpleadoPorId(id, bitacora);

            if(empleado != null){
                
            BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6003);

            bitacoraPlanilla.setAccion("Buscar");

            bitacoraPlanilla.setTablaAfectada("empleados");

            bitacoraPlanilla.setDescripcion(
            "Se Busqueda un empleado"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );

               

                txtCodigo.setText(String.valueOf(empleado.getEmpcodigo()));

                txtNombre.setText(empleado.getEmpnombre());

                txtDPI.setText(empleado.getEmpdpi());

                txtEstatus.setText(
                    String.valueOf(empleado.getPuecodigo())
                );

                
                if(empleado.getEmpestado() == 1){

                    cboEstatus.setSelectedItem("Activo");

                }else{

                    cboEstatus.setSelectedItem("Inactivo");
                }

            }else{

                JOptionPane.showMessageDialog(null, "Empleado no encontrado");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Ingrese un número válido");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null, "Seleccione un registro");
            return;
        }

        if(txtNombre.getText().trim().isEmpty() ||
            txtDPI.getText().trim().isEmpty() ||
            txtEstatus.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null, "Complete los campos");
            return;
        }

        try {

            clsCarreras empleado = new clsCarreras();

            empleado.setEmpcodigo(
                Integer.parseInt(txtCodigo.getText())
            );

            empleado.setEmpnombre(
                txtNombre.getText().trim()
            );

            empleado.setEmpdpi(
                txtDPI.getText().trim()
            );

            empleado.setPuecodigo(
                Integer.parseInt(txtEstatus.getText())
            );

            

            if(cboEstatus.getSelectedItem().toString().equals("Activo")){

                empleado.setEmpestado(1);

            }else{

                empleado.setEmpestado(0);
            }

            CarrerasDAO dao = new CarrerasDAO();

            clsBitacora bitacora = crearBitacora("Modificar empleado");

            int resultado = dao.actualizarEmpleado(empleado, bitacora);

            if(resultado > 0){
                
            BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6003);

            bitacoraPlanilla.setAccion("Modificar");

            bitacoraPlanilla.setTablaAfectada("empleados");

            bitacoraPlanilla.setDescripcion(
            "Se modificacion un empleado"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );

               

                JOptionPane.showMessageDialog(null, "Empleado modificado");

                llenadoDeTablas();

                limpiarTextos();

            }else{

                JOptionPane.showMessageDialog(null,
                    "No se pudo modificar");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,
                "Código inválido");

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(null,
                "Fecha inválida. Use YYYY-MM-DD");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(null,
                "Ingrese un código");

            return;
        }

        try {

            clsCarreras empleado = new clsCarreras();

            empleado.setEmpcodigo(
                Integer.parseInt(txtCodigo.getText())
            );

            CarrerasDAO dao = new CarrerasDAO();

            clsBitacora bitacora = crearBitacora("Eliminar empleado");

            int resultado = dao.eliminarEmpleado(empleado, bitacora);

            if(resultado > 0){
                
        BitacoraPlanillaDAO daoBitacora =
            new BitacoraPlanillaDAO();

            clsBitacoraPlanilla bitacoraPlanilla =
            new clsBitacoraPlanilla();

            bitacoraPlanilla.setCodigo(6003);

            bitacoraPlanilla.setAccion("Eliminar");

            bitacoraPlanilla.setTablaAfectada("empleados");

            bitacoraPlanilla.setDescripcion(
            "Se elimino un empleado"
            );

            bitacoraPlanilla.setUsuario("admin");

            daoBitacora.insertarBitacora(
            bitacoraPlanilla
            );

            

                JOptionPane.showMessageDialog(null,
                    "Empleado eliminado");

                llenadoDeTablas();

                limpiarTextos();

            }else{

                JOptionPane.showMessageDialog(null,
                    "No se pudo eliminar");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,
                "Código inválido");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        limpiarTextos();

        habilitarBotones();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPIActionPerformed

    private void btnayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayudaActionPerformed
        // TODO add your handling code here:
         try {

            String ruta = new File("src/main/java/Ayudas/Planillas/AyudaEmpleados.chm").getAbsolutePath();

            File archivo = new File(ruta);

            if (archivo.exists()) {

                Runtime.getRuntime().exec(
                    "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
                );

            } else {

                JOptionPane.showMessageDialog(this, "No se encontró el archivo de ayuda");

            }

        } catch (Exception ex) {

            ex.printStackTrace();

        }
    }//GEN-LAST:event_btnayudaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        Map p = new HashMap();
        JasperReport report;
        JasperPrint print;
        try {
            conn = Conexion.getConnection();
            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                + "/src/main/java/Reportes/ReportesPlanilla/Carreras.jrxml");
            print = JasperFillManager.fillReport(report, p, conn);
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("Reporte Prueba");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    
     public void habilitarBotones() {

        btnRegistrar.setEnabled(true);

        btnModificar.setEnabled(true);

        btnEliminar.setEnabled(true);
    }

    public void desHabilitarBotones() {

        btnRegistrar.setEnabled(false);

        btnModificar.setEnabled(false);

        btnEliminar.setEnabled(false);
    }

    public void esperar5min() {

        try {

            Thread.sleep(5 * 60 * 1000);

        } catch (Exception e) {

            System.out.println(e);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarreras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarreras;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDPI;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
