/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Bancos;
import java.io.File;
import java.sql.Connection;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @Angoly Camila Araujo Mayen 9959 - 24 - 17623
 */
public class frmBanco extends javax.swing.JInternalFrame {
private final Modelo.Bancos.BancoDAO bancoDAO = new Modelo.Bancos.BancoDAO();

    /**
     * Creates new form frmBanco
     */
   public frmBanco() {
     initComponents();
    setClosable(true);     
    setMaximizable(true);   
    setIconifiable(true);   
    cargarTabla();
    configurarSeleccionTabla();
    setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        actualizaar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        reporte = new javax.swing.JButton();
        label4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtbuscado = new javax.swing.JTextField();
        Limpiar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Dirección", "Teléfono", "Correo", "Fecha"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Dirección:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Teléfono");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Correo");

        jLabel5.setFont(new java.awt.Font("Swis721 Blk BT", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Bancos");
        jLabel5.setToolTipText("");

        agregar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        actualizaar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        actualizaar.setText("Actualizar");
        actualizaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaarActionPerformed(evt);
            }
        });

        buscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        reporte.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        reporte.setText("Reportes");
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label4.setText("ID:");

        btnBuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnBuscar.setText("Ayudas");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        Limpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(buscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(actualizaar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reporte, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(agregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(buscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label4)
                            .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(actualizaar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Limpiar)
                        .addGap(27, 27, 27)
                        .addComponent(reporte)
                        .addGap(34, 34, 34)
                        .addComponent(btnBuscar)
                        .addGap(159, 159, 159))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
    String ruta = "src\\main\\java\\Ayudas\\Bancos\\Ayuda Bancos.chm";

    File archivo = new File(ruta);

    if (archivo.exists()) {
        Runtime.getRuntime().exec("hh.exe \"" + ruta + "\"");
    } else {
        System.out.println("La ayuda no fue encontrada");
    }

} catch (Exception ex) {
    ex.printStackTrace();
}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
if (!camposCompletos()) return;

    try {
        Controlador.Bancos.clsBanco banco = getBancoDeFormulario();
        bancoDAO.insert(banco); // El ID y la fecha los genera la BD automáticamente
        javax.swing.JOptionPane.showMessageDialog(this,
            "Banco registrado correctamente.",
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        // ← AQUÍ se registra en la bitácora
        frmBitacoraBancaria.registrarBitacora(
            "INSERT", "Banco", null, null,
            "Nombre: " + jTextField1.getText().trim() +
            " | Dirección: " + jTextField2.getText().trim() +
            " | Teléfono: " + jTextField3.getText().trim() +
            " | Correo: " + jTextField4.getText().trim(),
            "Banco registrado"
        );
        cargarTabla();
        limpiarCampos();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al agregar: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        if (txtbuscado.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seleccione un banco de la tabla o ingrese un ID.",
            "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "¿Está seguro de que desea eliminar este banco?",
        "Confirmar eliminación", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    try {
        int id = Integer.parseInt(txtbuscado.getText().trim());
        bancoDAO.delete(id);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Banco eliminado correctamente.",
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        frmBitacoraBancaria.registrarBitacora(
    "DELETE",
    "Banco",
    Integer.parseInt(txtbuscado.getText().trim()),
    "Nombre: " + jTextField1.getText().trim(),
    null,
    "Banco eliminado"
);
        cargarTabla();
        limpiarCampos();
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "El ID debe ser un número válido.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al eliminar: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
          if (txtbuscado.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Ingrese un ID para buscar.",
            "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int id = Integer.parseInt(txtbuscado.getText().trim());
        Controlador.Bancos.clsBanco banco = bancoDAO.query(id);

        if (banco != null) {
            jTextField1.setText(banco.getBannombre());
            jTextField2.setText(banco.getBandireccion());
            jTextField3.setText(banco.getBantelefono());
            jTextField4.setText(banco.getBancorreo());
            frmBitacoraBancaria.registrarBitacora(
    "SELECT",
    "Banco",
    Integer.parseInt(txtbuscado.getText().trim()),
    null,
    null,
    "Consulta de banco por ID"
);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontró un banco con ID: " + id,
                "Sin resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        }
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "El ID debe ser un número válido.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al buscar: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_buscarActionPerformed

    private void actualizaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaarActionPerformed
        if (txtbuscado.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seleccione un banco de la tabla para actualizar.",
            "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!camposCompletos()) return;

    try {
        Controlador.Bancos.clsBanco banco = getBancoDeFormulario();
        banco.setBanid(Integer.parseInt(txtbuscado.getText().trim()));
        bancoDAO.update(banco);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Banco actualizado correctamente.",
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        frmBitacoraBancaria.registrarBitacora(
    "UPDATE",
    "Banco",
    Integer.parseInt(txtbuscado.getText().trim()),
    null,
    "Nombre: " + jTextField1.getText().trim() +
    " | Dirección: " + jTextField2.getText().trim() +
    " | Teléfono: " + jTextField3.getText().trim() +
    " | Correo: " + jTextField4.getText().trim(),
    "Banco actualizado"
);
        cargarTabla();
        limpiarCampos();
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "El ID debe ser un número válido.",
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al actualizar: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_actualizaarActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
       Connection conn = null;
    try {
        conn = Modelo.Conexion.getConnection();
        
        // Ruta corregida — faltaba el separador entre getAbsolutePath() y src
        String ruta = new java.io.File("").getAbsolutePath() 
                    + "\\src\\main\\java\\Reportes\\Bancos\\Banco.jrxml";
        
        System.out.println("Buscando reporte en: " + ruta); // Para verificar en consola
        
        java.io.File archivo = new java.io.File(ruta);
        if (!archivo.exists()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontró el archivo del reporte en:\n" + ruta,
                "Archivo no encontrado", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        java.util.Map<String, Object> parametros = new java.util.HashMap<>();
        
        net.sf.jasperreports.engine.JasperReport reporte =
           net.sf.jasperreports.engine.JasperCompileManager.compileReport(ruta);
        
        net.sf.jasperreports.engine.JasperPrint print =
           net.sf.jasperreports.engine.JasperFillManager.fillReport(reporte, parametros, conn);
        
        net.sf.jasperreports.engine.JasperExportManager.exportReportToPdfFile(print,"reporte.pdf");
        net.sf.jasperreports.swing.JRViewer viewer = new net.sf.jasperreports.swing.JRViewer(print);
        
        javax.swing.JFrame frame = new javax.swing.JFrame("Reporte de Clientes");
        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        frame.add(viewer);
        frame.setVisible(true);
        
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al generar el reporte:\n" + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } finally {
        if (conn != null) {
            try { conn.close(); } catch (Exception ex) { ex.printStackTrace(); }
        }
    }
    }//GEN-LAST:event_reporteActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
         int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "¿Está seguro de que desea ELIMINAR TODOS los bancos de la base de datos?\n"
        + "Esta acción no se puede deshacer.",
        "Confirmar limpieza total",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.WARNING_MESSAGE);

    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    try {
        bancoDAO.deleteAll();

        // Registrar en bitácora
        frmBitacoraBancaria.registrarBitacora(
            "DELETE ALL", "Banco", null, null, null,
            "Se eliminaron todos los registros de la tabla Banco"
        );

        javax.swing.JOptionPane.showMessageDialog(this,
            "Todos los registros fueron eliminados.",
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        cargarTabla();
        limpiarCampos();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al limpiar la tabla: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_LimpiarActionPerformed
 // ── Llena la tabla con todos los bancos ──────────────────────
private void cargarTabla() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new String[]{"ID", "Nombre", "Dirección", "Teléfono", "Correo", "Fecha"}, 0
    ) {
        @Override
        public boolean isCellEditable(int r, int c) { return false; }
    };

    for (Controlador.Bancos.clsBanco b : bancoDAO.listar()) {
        modelo.addRow(new Object[]{
            b.getBanid(),
            b.getBannombre(),
            b.getBandireccion(),
            b.getBantelefono(),
            b.getBancorreo(),
            b.getBanfecharegistro()  // La fecha viene de la BD, el usuario no la escribe
        });
    }
    jTable2.setModel(modelo);
}

// ── Clic en fila → llena campos automáticamente ──────────────
private void configurarSeleccionTabla() {
    jTable2.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting() && jTable2.getSelectedRow() != -1) {
            int fila = jTable2.getSelectedRow();
            txtbuscado.setText(jTable2.getValueAt(fila, 0).toString()); // ID automático
            jTextField1.setText(jTable2.getValueAt(fila, 1).toString());
            jTextField2.setText(jTable2.getValueAt(fila, 2).toString());
            jTextField3.setText(jTable2.getValueAt(fila, 3).toString());
            jTextField4.setText(jTable2.getValueAt(fila, 4).toString());
        }
    });
}

// ── Limpia todos los campos ──────────────────────────────────
private void limpiarCampos() {
    txtbuscado.setText("");
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTable2.clearSelection();
}

// ── Valida que los campos no estén vacíos ────────────────────
private boolean camposCompletos() {
    if (jTextField1.getText().trim().isEmpty() ||
        jTextField2.getText().trim().isEmpty() ||
        jTextField3.getText().trim().isEmpty() ||
        jTextField4.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Complete todos los campos: Nombre, Dirección, Teléfono y Correo.",
            "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return false;
    }
    return true;
}

// ── Crea el objeto clsBanco desde los campos del formulario ──
private Controlador.Bancos.clsBanco getBancoDeFormulario() {
    Controlador.Bancos.clsBanco b = new Controlador.Bancos.clsBanco();
    b.setBannombre(jTextField1.getText().trim());
    b.setBandireccion(jTextField2.getText().trim());
    b.setBantelefono(jTextField3.getText().trim());
    b.setBancorreo(jTextField4.getText().trim());
    // No se setea Banid ni Banfecharegistro → los genera MySQL con AUTO_INCREMENT y DEFAULT NOW()
    return b;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton actualizaar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton buscar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel label4;
    private javax.swing.JButton reporte;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
