/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Bancos;
//Modificado Por Angoly Camila Araujo Mayen 9959-24-17623

import Vista.*;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author visitante
 */
public class MdiBancos extends javax.swing.JFrame {
    
    

    /**
     * Creates new form MdiGeneral
     */
    public MdiBancos() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MdiBancos.MAXIMIZED_BOTH);
        this.setTitle("");
        cerrar();
        
        //setDefaultCloseOperation(EXIT_ON_CLOSE);
    
        
    //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    
    //Agregadopor Astrid para cargar permisos del usuario conectado al abrir el MDI
    //Agreguen los permisos correspondientes a un usuario y luego quitan los comentarios de las lineas de abajo, si no va les va aparcer bloqueado
    //int usuId = clsUsuarioConectado.getUsuId();
    //PermisosDAO permisosDAO = new PermisosDAO();
    //List<Integer> appsPermitidas = permisosDAO.obtenerAplicacionesPermitidas(usuId);
    //configurarVisibilidadBotones(appsPermitidas);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        mnuGeneral = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalirSistema = new javax.swing.JCheckBoxMenuItem();
        mnuCatalogos = new javax.swing.JMenu();
        mnuCatalogosMantenimientos = new javax.swing.JMenu();
        mantenimientoBancos = new javax.swing.JMenuItem();
        frmMantenimientoClientes = new javax.swing.JMenuItem();
        frmMantenimientoTipoCuenta = new javax.swing.JMenuItem();
        mnuProcesos = new javax.swing.JMenu();
        frmMantenimientoConciliacionBancaria = new javax.swing.JMenuItem();
        frmProcesoAplicacionPerfil = new javax.swing.JMenuItem();
        frmMantenimientoCatEstadoConciliacion = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        frmMantenimientoCatTipoTransaccion = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        frmMantenimientoBitacora = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");
        mnuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoActionPerformed(evt);
            }
        });

        mnuSalirSistema.setSelected(true);
        mnuSalirSistema.setText("Salir del Sistema");
        mnuSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirSistemaActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalirSistema);

        mnuGeneral.add(mnuArchivo);

        mnuCatalogos.setText("Catalogos");

        mnuCatalogosMantenimientos.setText("Mantenimientos");
        mnuCatalogosMantenimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCatalogosMantenimientosActionPerformed(evt);
            }
        });

        mantenimientoBancos.setText("Mantenimiento Bancos");
        mantenimientoBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimientoBancosActionPerformed(evt);
            }
        });
        mnuCatalogosMantenimientos.add(mantenimientoBancos);

        frmMantenimientoClientes.setText("Mantenimiento Clientes");
        frmMantenimientoClientes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                frmMantenimientoClientesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        frmMantenimientoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMantenimientoClientesActionPerformed(evt);
            }
        });
        mnuCatalogosMantenimientos.add(frmMantenimientoClientes);

        frmMantenimientoTipoCuenta.setText("Mantenimiento Tipo Cuenta");
        frmMantenimientoTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMantenimientoTipoCuentaActionPerformed(evt);
            }
        });
        mnuCatalogosMantenimientos.add(frmMantenimientoTipoCuenta);

        mnuCatalogos.add(mnuCatalogosMantenimientos);

        mnuGeneral.add(mnuCatalogos);

        mnuProcesos.setText("Procesos");
        mnuProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProcesosActionPerformed(evt);
            }
        });

        frmMantenimientoConciliacionBancaria.setText("Asignacion Movimiento Bancario");
        frmMantenimientoConciliacionBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMantenimientoConciliacionBancariaActionPerformed(evt);
            }
        });
        mnuProcesos.add(frmMantenimientoConciliacionBancaria);

        frmProcesoAplicacionPerfil.setText("Asignacion Cuenta Bancaria");
        frmProcesoAplicacionPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmProcesoAplicacionPerfilActionPerformed(evt);
            }
        });
        mnuProcesos.add(frmProcesoAplicacionPerfil);

        frmMantenimientoCatEstadoConciliacion.setText("Asignacion Estado Conciliación");
        frmMantenimientoCatEstadoConciliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMantenimientoCatEstadoConciliacionActionPerformed(evt);
            }
        });
        mnuProcesos.add(frmMantenimientoCatEstadoConciliacion);

        jMenuItem3.setText("Asignacion Conciliación Bancaria");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuProcesos.add(jMenuItem3);

        frmMantenimientoCatTipoTransaccion.setText("Asignación Transacción");
        frmMantenimientoCatTipoTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMantenimientoCatTipoTransaccionActionPerformed(evt);
            }
        });
        mnuProcesos.add(frmMantenimientoCatTipoTransaccion);

        mnuGeneral.add(mnuProcesos);

        mnuConsultas.setText("Consultas");
        mnuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultasActionPerformed(evt);
            }
        });

        frmMantenimientoBitacora.setText("Consulta Bitacora Bancaria");
        frmMantenimientoBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMantenimientoBitacoraActionPerformed(evt);
            }
        });
        mnuConsultas.add(frmMantenimientoBitacora);

        mnuGeneral.add(mnuConsultas);

        setJMenuBar(mnuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cerrar(){
        try 
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() 
            {
                public void windowClosing(WindowEvent e) 
                {
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        } catch (Exception e) 
        {
            e.printStackTrace();
        }
    }    
    public void confirmarSalida() 
    {
        int valor=JOptionPane.showConfirmDialog(this,"¿Està seguro de cerrar?", "Advertencia", JOptionPane.YES_NO_OPTION);
                    if (valor==JOptionPane.YES_OPTION) 
                    {
                        JOptionPane.showMessageDialog(null, "Gracias por su visita, hasta pronto", "Gracias", JOptionPane.INFORMATION_MESSAGE);
                        System.exit(0);
                    }
    }
    
  
     // Método para bloquear o desbloquear opciones según los permisos
public void configurarVisibilidadBotones(List<Integer> appsPermitidas) {
    
    mantenimientoBancos.setEnabled(false);
    frmMantenimientoClientes.setEnabled(false);
    frmMantenimientoTipoCuenta.setEnabled(false);
    frmMantenimientoBitacora.setEnabled(false);
    frmMantenimientoConciliacionBancaria.setEnabled(false);
    frmProcesoAplicacionPerfil.setEnabled(false);
    frmMantenimientoCatEstadoConciliacion.setEnabled(false);
    frmMantenimientoConciliacionBancaria.setEnabled(false);
    frmMantenimientoCatTipoTransaccion.setEnabled(false);
    frmMantenimientoCatEstadoConciliacion.setEnabled(false);

    // Recorre la lista y enciende las que el usuario tenga asignadas
    for (int codigoApp : appsPermitidas) {
        switch (codigoApp) {
            case 10: // Código numérico le pertenece a cada ventana
                mantenimientoBancos.setEnabled(true);
                break;
            case 10007:
                frmMantenimientoClientes.setEnabled(true);
                break;
            case 11:
                frmMantenimientoTipoCuenta.setEnabled(true);
                break;
            case 10005:
                frmMantenimientoBitacora.setEnabled(true);
                break;
            case 10010:
                frmMantenimientoConciliacionBancaria.setEnabled(true);
                break;
            case 10011:
                frmProcesoAplicacionPerfil.setEnabled(true);
                break;
            case 10012:
                frmMantenimientoCatEstadoConciliacion.setEnabled(true);
                break;
            case 10020:
                frmMantenimientoConciliacionBancaria.setEnabled(true);
                break;
            case 10021:
                frmMantenimientoCatTipoTransaccion.setEnabled(true);
                break;
            case 10022:
                frmMantenimientoCatEstadoConciliacion.setEnabled(true);
                break;
        }
    }
}
    
    
    
    
    private void mnuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuArchivoActionPerformed

    private void mnuSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirSistemaActionPerformed
        // TODO add your handling code here:
                /*===== OPERACIÓN CERRAR SESIÓN ====
          Variable entera respuesta_cs*/

        int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea Cerrar Sesión?", "Cerrar Sesión",            JOptionPane.YES_NO_OPTION);

        if (respuesta_cs == 0) {
            this.dispose();
        }        
    }//GEN-LAST:event_mnuSalirSistemaActionPerformed

    private void mnuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuConsultasActionPerformed

    private void mnuProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProcesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuProcesosActionPerformed

    private void mnuCatalogosMantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCatalogosMantenimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCatalogosMantenimientosActionPerformed

    private void mantenimientoBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimientoBancosActionPerformed
       System.out.println("Abriendo Mantenimiento Bancos");
    frmBanco ventana = new frmBanco();
    jDesktopPane1.add(ventana);
    java.awt.Dimension desktopSize = jDesktopPane1.getSize();
    java.awt.Dimension frameSize   = ventana.getSize();
    ventana.setLocation(
        (desktopSize.width  - frameSize.width)  / 2,
        (desktopSize.height - frameSize.height) / 2
    );
    ventana.setVisible(true);
    }//GEN-LAST:event_mantenimientoBancosActionPerformed

    private void frmMantenimientoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMantenimientoClientesActionPerformed
       
        System.out.println("Abriendo Mantenimiento Clientes");
    frmCliente ventana = new frmCliente();
    jDesktopPane1.add(ventana);
    java.awt.Dimension desktopSize = jDesktopPane1.getSize();
    java.awt.Dimension frameSize   = ventana.getSize();
    ventana.setLocation(
        (desktopSize.width  - frameSize.width)  / 2,
        (desktopSize.height - frameSize.height) / 2
    );
    ventana.setVisible(true);
    }//GEN-LAST:event_frmMantenimientoClientesActionPerformed

    private void frmMantenimientoClientesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_frmMantenimientoClientesAncestorAdded
        
      
    }//GEN-LAST:event_frmMantenimientoClientesAncestorAdded

    private void frmMantenimientoTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMantenimientoTipoCuentaActionPerformed
    System.out.println("Abriendo Mantenimiento Tipo Cuenta");

    frmMantenimientoTipoCuenta ventana = new frmMantenimientoTipoCuenta();

    ventana.pack();

    jDesktopPane1.add(ventana);

    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension frameSize = ventana.getSize();

    ventana.setLocation(
        (desktopSize.width - frameSize.width) / 2,
        (desktopSize.height - frameSize.height) / 2
    );

    ventana.setVisible(true);
    }//GEN-LAST:event_frmMantenimientoTipoCuentaActionPerformed

    private void frmMantenimientoBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMantenimientoBitacoraActionPerformed
        System.out.println("Abriendo Bitácora Bancaria");
    frmBitacoraBancaria ventana = new frmBitacoraBancaria();
    jDesktopPane1.add(ventana);
    java.awt.Dimension desktopSize = jDesktopPane1.getSize();
    java.awt.Dimension frameSize   = ventana.getSize();
    ventana.setLocation(
        (desktopSize.width  - frameSize.width)  / 2,
        (desktopSize.height - frameSize.height) / 2
    );
    ventana.setVisible(true);
    }//GEN-LAST:event_frmMantenimientoBitacoraActionPerformed

    private void frmMantenimientoConciliacionBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMantenimientoConciliacionBancariaActionPerformed
    System.out.println("Abriendo Movimiento Bancario");

    frmMovimientoBancario ventana = new frmMovimientoBancario();
    jDesktopPane1.add(ventana);

    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension FrameSize = ventana.getSize();

    ventana.setLocation(
        (desktopSize.width - FrameSize.width) / 2,
        (desktopSize.height - FrameSize.height) / 2
    );

    ventana.setVisible(true);
    }//GEN-LAST:event_frmMantenimientoConciliacionBancariaActionPerformed

    private void frmProcesoAplicacionPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmProcesoAplicacionPerfilActionPerformed
    System.out.println("Abriendo Cuenta Bancaria");

    frmCuentaBancaria vista = new frmCuentaBancaria();

    jDesktopPane1.add(vista);

    java.awt.Dimension desktopSize = jDesktopPane1.getSize();
    java.awt.Dimension frameSize = vista.getSize();

    vista.setLocation(
    (desktopSize.width - frameSize.width) / 2,
    (desktopSize.height - frameSize.height) / 2
    );

vista.setVisible(true);
    }//GEN-LAST:event_frmProcesoAplicacionPerfilActionPerformed

    private void frmMantenimientoCatEstadoConciliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMantenimientoCatEstadoConciliacionActionPerformed
        frmCatEstadoConciliacion ventana = new frmCatEstadoConciliacion();
    jDesktopPane1.add(ventana);
    ventana.setVisible(true);
    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension FrameSize = ventana.getSize();
    ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
    }//GEN-LAST:event_frmMantenimientoCatEstadoConciliacionActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    System.out.println("Abriendo Mantenimiento Conciliacion Bancaria");

    frmConciliacionBancaria ventana = new frmConciliacionBancaria();

    ventana.pack();

    jDesktopPane1.add(ventana);

    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension frameSize = ventana.getSize();

    ventana.setLocation(
        (desktopSize.width - frameSize.width) / 2,
        (desktopSize.height - frameSize.height) / 2
    );

    ventana.setVisible(true);        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void frmMantenimientoCatTipoTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMantenimientoCatTipoTransaccionActionPerformed
   System.out.println("Abriendo Mantenimiento Tipo Transaccion");

    frmCatTipoTransaccion ventana = new frmCatTipoTransaccion();

    ventana.pack();

    jDesktopPane1.add(ventana);

    Dimension desktopSize = jDesktopPane1.getSize();
    Dimension frameSize = ventana.getSize();

    ventana.setLocation(
        (desktopSize.width - frameSize.width) / 2,
        (desktopSize.height - frameSize.height) / 2
    );

    ventana.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_frmMantenimientoCatTipoTransaccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiBancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiBancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiBancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiBancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiBancos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem frmMantenimientoBitacora;
    private javax.swing.JMenuItem frmMantenimientoCatEstadoConciliacion;
    private javax.swing.JMenuItem frmMantenimientoCatTipoTransaccion;
    private javax.swing.JMenuItem frmMantenimientoClientes;
    private javax.swing.JMenuItem frmMantenimientoConciliacionBancaria;
    private javax.swing.JMenuItem frmMantenimientoTipoCuenta;
    private javax.swing.JMenuItem frmProcesoAplicacionPerfil;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem mantenimientoBancos;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuCatalogos;
    private javax.swing.JMenu mnuCatalogosMantenimientos;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenuBar mnuGeneral;
    private javax.swing.JMenu mnuProcesos;
    private javax.swing.JCheckBoxMenuItem mnuSalirSistema;
    // End of variables declaration//GEN-END:variables
}
