/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vista.ComisionVenta;
import Controlador.clsUsuarioConectado;
import Modelo.PermisosDAO;
import Vista.ComisionVenta.frmCalculoComisiones;
import Vista.frmLogin;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel R
 */
public class frmComisionesVentas extends javax.swing.JFrame {

    /**
     * Creates new form frmComisionesVentas
     */
    public frmComisionesVentas() {
        initComponents();
                 setLocationRelativeTo(null);
        this.setExtendedState(frmComisionesVentas.MAXIMIZED_BOTH);
        this.setTitle("");
        cerrar();

    }

     public void cerrar(){
        try 
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() 
            {
                public void windowClosing(WindowEvent e) 
                {
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        } catch (Exception e) 
        {
            e.printStackTrace();
        }
    }
     
             public void confirmarSalida() 
    {
        int valor=JOptionPane.showConfirmDialog(this,"¿Està seguro de cerrar?", "Advertencia", JOptionPane.YES_NO_OPTION);
                    if (valor==JOptionPane.YES_OPTION) 
                    {
                        JOptionPane.showMessageDialog(null, "Gracias por su visita, hasta pronto", "Gracias", JOptionPane.INFORMATION_MESSAGE);
                        System.exit(0);
                    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComisionesEscritorio = new javax.swing.JDesktopPane();
        MenuComisionVen = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        PComision = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        CReporte = new javax.swing.JMenu();
        frmReportes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        BitacoraCV = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComisionesEscritorio.setLayout(new java.awt.BorderLayout());

        jMenu3.setText("Archivo");

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        MenuComisionVen.add(jMenu3);

        PComision.setText("Procesos Comisiones");
        PComision.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                PComisionMenuSelected(evt);
            }
        });
        PComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PComisionActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Calculo de Comisiones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        PComision.add(jMenuItem1);

        MenuComisionVen.add(PComision);

        CReporte.setText("Reportes de comisiones");
        CReporte.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                CReporteMenuSelected(evt);
            }
        });
        CReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CReporteActionPerformed(evt);
            }
        });

        frmReportes.setText("Reportes");
        frmReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmReportesActionPerformed(evt);
            }
        });
        CReporte.add(frmReportes);

        MenuComisionVen.add(CReporte);

        jMenu1.setText("Consultas");

        BitacoraCV.setText("Consultar Comisiones");
        BitacoraCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BitacoraCVActionPerformed(evt);
            }
        });
        jMenu1.add(BitacoraCV);

        MenuComisionVen.add(jMenu1);

        jMenu2.setText("Ayudas");

        jMenuItem2.setText("VerAyudas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        MenuComisionVen.add(jMenu2);

        setJMenuBar(MenuComisionVen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(ComisionesEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addContainerGap(633, Short.MAX_VALUE))

        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(ComisionesEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PComisionMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_PComisionMenuSelected
        // TODO add your handling code here:  
    }//GEN-LAST:event_PComisionMenuSelected

    private void CReporteMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_CReporteMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_CReporteMenuSelected

    private void PComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PComisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PComisionActionPerformed

    private void CReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CReporteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CReporteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.out.println("entre a mantenimiento usuarios");
        frmCalculoComisiones ventana = new frmCalculoComisiones();
        ComisionesEscritorio.add(ventana);
        Dimension desktopSize = ComisionesEscritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void frmReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmReportesActionPerformed
        // TODO add your handling code here:
        System.out.println("entre a mantenimiento usuarios");
        frmReportes ventana = new frmReportes();
        ComisionesEscritorio.add(ventana);
        Dimension desktopSize = ComisionesEscritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        ventana.setVisible(true);
    }//GEN-LAST:event_frmReportesActionPerformed

    private void BitacoraCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BitacoraCVActionPerformed
        // TODO add your handling code here:
        System.out.println("entre a mantenimiento usuarios");
        frmBitacoraComisionesVentas ventana = new frmBitacoraComisionesVentas();
        ComisionesEscritorio.add(ventana);
        Dimension desktopSize = ComisionesEscritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        ventana.setVisible(true);
    }//GEN-LAST:event_BitacoraCVActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    try {
        // Buscamos el archivo en la raíz del proyecto
        java.nio.file.Path rutaCompilada = java.nio.file.Path.of("ayudaComisionReporte.chm");
        
        if (java.nio.file.Files.exists(rutaCompilada)) {
            // "hh.exe" es el visor de Windows para archivos CHM
            new ProcessBuilder("hh.exe", rutaCompilada.toAbsolutePath().toString()).start();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No se encontró el archivo en:\n" + rutaCompilada.toAbsolutePath(), 
                "Error de Ruta", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir ayuda: " + e.getMessage());
    }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Desea cerrar sesión?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION
        );

        if (respuesta == JOptionPane.YES_OPTION) {

            JOptionPane.showMessageDialog(
                    this,
                    "Sesión de comisines de ventas finalizada correctamente"
            );

            frmLogin login = new frmLogin();

            login.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmComisionesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmComisionesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmComisionesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmComisionesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmComisionesVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BitacoraCV;
    private javax.swing.JMenu CReporte;
    private javax.swing.JDesktopPane ComisionesEscritorio;
    private javax.swing.JMenuBar MenuComisionVen;
    private javax.swing.JMenu PComision;
    private javax.swing.JMenuItem frmReportes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
